import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1700,height:1200}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.addInitScript(()=>localStorage.setItem('lunar-link-config-v1.2',JSON.stringify({mountX:0.65,mountY:0.76,mountZ:0.45})));
const glbJSON=buffer=>{assert.equal(buffer.toString('ascii',0,4),'glTF');assert.equal(buffer.readUInt32LE(4),2);assert.equal(buffer.readUInt32LE(8),buffer.length);assert.equal(buffer.readUInt32LE(16),0x4e4f534a);return JSON.parse(buffer.toString('utf8',20,20+buffer.readUInt32LE(12)));};
try{
  await page.goto(process.env.TEST_URL||'http://127.0.0.1:4173',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.lunarLink?.webgl);
  assert.deepEqual(await page.evaluate(()=>[window.lunarLink.config.mountX,window.lunarLink.config.mountY,window.lunarLink.config.mountZ]),[0.92,0.76,0.62]);
  await page.locator('[data-preset="nominal"]').click();await page.locator('#rewind').click();
  assert.equal(await page.locator('#show-zones').isChecked(),true);
  await mkdir('test-results',{recursive:true});await mkdir('examples',{recursive:true});
  const before=await page.evaluate(()=>JSON.stringify(window.lunarLink.result.summary));
  await page.locator('#scene').scrollIntoViewIfNeeded();await page.waitForTimeout(350);
  await page.locator('.viewport-card').screenshot({path:'test-results/brochure-overview.png'});
  await page.locator('[data-view="underside"]').click();await page.waitForTimeout(400);
  await page.locator('.viewport-card').screenshot({path:'test-results/brochure-underside.png'});
  await page.locator('[data-view="top"]').click();await page.waitForTimeout(300);
  await page.locator('.viewport-card').screenshot({path:'test-results/brochure-top.png'});
  await page.locator('#studio-view').check();
  for(const [view,label] of [['orbit','isometric'],['top','top'],['front','side'],['underside','bottom']]){
    await page.locator(`[data-view="${view}"]`).click();await page.waitForTimeout(250);
    await page.locator('.viewport-card').screenshot({path:`test-results/reference-${label}.png`});
  }
  await page.locator('#studio-view').uncheck();
  await page.locator('[data-view="mount"]').click();await page.waitForTimeout(300);
  await page.locator('.viewport-card').screenshot({path:'test-results/brochure-our-payload.png'});
  // Complete export must work even while the host is hidden in isolated 2U view.
  await page.locator('[data-view="detail"]').click();
  const download=page.waitForEvent('download');await page.locator('#export-model').click();const model=await download;
  await model.saveAs('examples/ispace-photo-concept-with-our-2u.glb');
  const full=glbJSON(await readFile(await model.path()));
  assert.equal(full.nodes.filter(n=>n.name==='Six through-hole equipment face').length,2);
  assert.equal(full.nodes.filter(n=>n.name==='External X brace').length,2);
  await page.locator('#toast').evaluate(e=>e.style.display='none');
  for(const name of ['Power input / DC-DC','Motor drivers / current sense','MCU / attitude / encoder interface','Thermal strap to lander interface','Lander power / data input'])assert.ok(full.nodes.some(n=>n.name===name),name);
  await page.locator('#payload-cover').uncheck();await page.waitForTimeout(200);
  await page.locator('.viewport-card').screenshot({path:'test-results/payload-circuit-detail.png'});
  await page.locator('#explode').check();await page.waitForTimeout(200);
  await page.locator('.viewport-card').screenshot({path:'test-results/payload-circuit-exploded.png'});
  await page.locator('#explode').uncheck();await page.locator('#payload-cover').check();
  assert.match(await page.locator('#design-fit-summary').textContent(),/INTERFERENCE FOUND/);
  assert.match(await page.locator('#design-bus-summary').textContent(),/CURRENT \/ INRUSH EXCEEDS/);
  const studyDownload=page.waitForEvent('download');await page.locator('#export-design').click();const studyFile=await studyDownload;
  await studyFile.saveAs('examples/payload-design-study.json');
  const study=JSON.parse(await readFile(await studyFile.path(),'utf8'));
  assert.equal(study.modelVersion,'1.4.2');assert.equal(study.assembly.allSampledFit,false);assert.equal(study.electrical.outagePass,false);
  assert.equal(study.config.mountX,0.92);assert.equal(study.config.mountZ,0.62);
  await page.locator('.design-card').first().screenshot({path:'test-results/payload-assembly-study.png'});
  await page.locator('.design-card').last().screenshot({path:'test-results/payload-power-study.png'});
  assert.ok(full.nodes.some(n=>n.name==='Orbiter / red'));assert.equal(full.nodes.filter(n=>n.name?.startsWith('Bottom blue')).length,2);
  assert.equal(full.nodes.filter(n=>n.name?.startsWith('Bottom yellow')).length,8);assert.ok(full.nodes.some(n=>n.name==='Top green spare'));
  assert.ok(full.materials.some(m=>m.pbrMetallicRoughness?.baseColorFactor?.[1]>m.pbrMetallicRoughness?.baseColorFactor?.[0]&&m.pbrMetallicRoughness?.baseColorFactor?.[2]>m.pbrMetallicRoughness?.baseColorFactor?.[0]));
  const metadata=full.nodes.find(n=>n.extras?.payloadAllocations);assert.equal(metadata.extras.units,'metres');assert.equal(metadata.extras.payloadAllocations.length,12);
  await page.locator('#show-zones').uncheck();const minimalDownload=page.waitForEvent('download');await page.locator('#export-model').click();const minimal=glbJSON(await readFile(await(await minimalDownload).path()));
  assert.ok(!minimal.nodes.some(n=>n.name==='Orbiter / red'));assert.equal(await page.evaluate(()=>JSON.stringify(window.lunarLink.result.summary)),before);
  const currentLimit=page.locator('#p-busCurrentLimitA');await currentLimit.evaluate(e=>e.closest('details').open=true);
  await currentLimit.fill('1');await currentLimit.dispatchEvent('change');
  await page.waitForFunction(()=>window.lunarLink.result.config.busCurrentLimitA===1);
  assert.match(await page.locator('#design-bus-summary').textContent(),/WITHIN CURRENT ALLOCATION/);
  await currentLimit.fill('0.5');await currentLimit.dispatchEvent('change');
  await page.waitForFunction(()=>window.lunarLink.result.config.busCurrentLimitA===0.5);
  assert.match(await page.locator('#design-bus-summary').textContent(),/CURRENT \/ INRUSH EXCEEDS/);
  await page.locator('[data-view="orbit"]').click();await page.locator('#show-zones').check();
  await page.locator('#toast').evaluate(e=>e.style.display='none');
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('.viewport-card').screenshot({path:'test-results/brochure-mobile.png'});
  assert.deepEqual(errors,[]);console.log('PASS brochure/payload: all views, GLB 12 allocations and 3 PCBs, cutaway/exploded views, fit/bus diagnostics and input update, study export, visibility invariant and mobile layout.');
}finally{await browser.close();}
