import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';

const base=process.env.TEST_URL||'http://127.0.0.1:5173';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1512,height:1120},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
try {
  await page.goto(base,{waitUntil:'networkidle'});
  await page.waitForFunction(()=>window.lunarLink?.result);
  assert.equal(await page.evaluate(()=>window.lunarLink.webgl),true,'WebGL scene should initialize');
  assert.equal(await page.locator('#scene canvas').count(),1);
  await page.locator('#timeline').fill('12');await page.locator('#timeline').dispatchEvent('input');
  await page.waitForTimeout(150);
  assert.match(await page.locator('#insight b').textContent(),/maintains communication/);
  await mkdir('test-results',{recursive:true});
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  await page.locator('#play').click();await page.waitForTimeout(300);await page.locator('#play').click();
  assert.ok(Number(await page.locator('#timeline').inputValue())>12,'Playback advances');
  await page.locator('#explode').check();await page.locator('[data-view="detail"]').click();await page.locator('#explode').uncheck();
  await page.locator('[data-preset="jam"]').click();await page.locator('#timeline').fill('12');await page.locator('#timeline').dispatchEvent('input');
  assert.match(await page.locator('#system-status').textContent(),/JAMMED/);
  await page.locator('[data-preset="tilt"]').click();await page.locator('#rewind').click();
  await page.locator('#p-pitch').fill('-25');await page.locator('#p-pitch').dispatchEvent('change');
  await page.waitForFunction(()=>window.lunarLink.result.config.pitch===-25);
  await page.locator('#p-duration').fill('6');await page.locator('#p-duration').dispatchEvent('change');
  await page.waitForFunction(()=>window.lunarLink.result.config.duration===6);
  await page.locator('[data-tab="radio"]').click();
  assert.match(await page.locator('#budget-table').textContent(),/Link margin/);
  assert.match(await page.locator('#patch-result').textContent(),/PATCH WIDTH/);
  assert.match(await page.locator('#beam-detail').textContent(),/FSPL/);
  await page.locator('#antenna-profile').selectOption('tigrisat');
  await page.waitForFunction(()=>window.lunarLink.config.frequencyGHz===2.45);
  await page.locator('#antenna-profile').selectOption('anser');
  await page.locator('#patch-er').fill('4.4');await page.locator('#patch-er').dispatchEvent('input');
  await page.locator('#file-pattern').setInputFiles({name:'pattern.csv',mimeType:'text/csv',buffer:Buffer.from('angle_deg,gain_dbi\n0,12\n30,6\n90,-20\n180,-28')});
  await page.waitForFunction(()=>window.lunarLink.config.pattern?.length===4);
  assert.match(await page.locator('#pattern-source').textContent(),/IMPORTED/);
  await page.locator('#clear-pattern').click();
  await page.locator('[data-tab="environment"]').click();await page.locator('#run-thermal').click();
  assert.match(await page.locator('#thermal-results').textContent(),/Minimum/);
  assert.ok(await page.evaluate(()=>window.lunarLink.thermal.frames.length>10));
  await page.locator('[data-tab="analysis"]').click();await page.locator('#run-step').click();
  assert.ok(await page.evaluate(()=>window.lunarLink.stepResponse.settlingMs>50));assert.match(await page.locator('#step-results').textContent(),/FAIL/);
  await page.locator('[data-preset="tilt"]').click();
  await page.locator('#batch-count').selectOption('50');await page.locator('#run-batch').click();
  await page.waitForFunction(()=>window.lunarLink.batch?.rows.length===50,{},{timeout:90000});
  assert.match(await page.locator('#batch-results').textContent(),/Wilson/);
  await page.locator('[data-tab="evidence"]').click();assert.match(await page.locator('#requirements').textContent(),/NOT VERIFIED/);
  const dl=page.waitForEvent('download');await page.locator('#export-report').click();const report=await dl;assert.match(report.suggestedFilename(),/\.md$/);
  await page.locator('.export-menu summary').click();const csvDownload=page.waitForEvent('download');await page.locator('[data-export="csv"]').click();assert.match((await csvDownload).suggestedFilename(),/\.csv$/);
  const invalid={...await page.evaluate(()=>window.lunarLink.config),inertia:0};
  await page.locator('#file-config').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});
  await page.waitForTimeout(100);assert.match(await page.locator('#toast').textContent(),/inertia/);
  const valid={...await page.evaluate(()=>window.lunarLink.config),pitch:-20};
  await page.locator('#file-config').setInputFiles({name:'scenario.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({config:valid}))});
  await page.waitForFunction(()=>window.lunarLink.result.config.pitch===-20);
  await page.locator('[data-tab="mission"]').click();await page.locator('[data-preset="tilt"]').click();await page.locator('#timeline').fill('12');await page.locator('#timeline').dispatchEvent('input');
  await page.locator('[data-view="detail"]').click();await page.waitForTimeout(200);await page.screenshot({path:'test-results/payload-2u.png',fullPage:true});
  await page.locator('[data-preset="inverted"]').click();await page.locator('#timeline').fill('18');await page.locator('#timeline').dispatchEvent('input');
  assert.match(await page.locator('#live-los').textContent(),/GROUND/);
  await page.locator('[data-preset="tilt"]').click();await page.locator('#timeline').fill('12');await page.locator('#timeline').dispatchEvent('input');
  await page.locator('[data-view="orbit"]').click();await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal page overflow on mobile');
  await page.screenshot({path:'test-results/mobile.png',fullPage:true});
  assert.deepEqual(errors,[],'No browser runtime errors');
  console.log('PASS: WebGL, playback, scenario switching, numeric controls, RF/patch, pattern import, thermal study, 50-trial worker, reports, CSV, validated config imports and mobile layout.');
} finally {await browser.close();}
