import {assemblyFit,assemblyStudy,electricalStudy} from './payload-design.js';
import {lineChart} from './charts.js';
const $=s=>document.querySelector(s),f=(x,n=2)=>Number.isFinite(x)?x.toFixed(n):'—';
export const designHTML=`<article class="card design-card"><div class="card-heading"><h2>2U assembly screening · frame, motors & RF cable</h2><button class="button" id="export-design">Export design study</button></div><div class="card-padding"><p>Host-powered concept: no payload battery or onboard heater. Three illustrative PCBs: power protection/DC-DC, two motor drivers, MCU/attitude/encoder interface. Board size 80 × 78 mm; this is a component allocation, not routed or qualified electronics.</p><div class="power-architecture"><span>Lander power → protection → DC/DC → logic + drivers → gimbal</span><span>Lander RF → flex coax → antenna</span><span>Lander heated base → mount + thermal strap → payload</span></div><div id="design-fit-summary"></div><div id="design-current"></div><canvas id="assembly-map" class="assembly-map" aria-label="Sampled azimuth elevation assembly fit map" role="img"></canvas><p class="small-note">Azimuth horizontally / elevation vertically. Green = fits the concept proxies; red = interference / cable allocation exceeded. Percentage is sampled grid coverage, not mission success. Plate-only simulation limits remain separate; no exact CAD collision, continuous trajectory planning or cable stress solved.</p><div id="design-size-comparison"></div></div></article><article class="card design-card"><div class="card-heading"><h2>Lander bus interface · drop, current & brief outage</h2></div><div class="card-padding"><div id="design-bus-summary"></div><canvas id="hold-up-chart" class="chart" aria-label="Ideal input capacitor voltage during host bus outage" role="img"></canvas><p class="small-note">V vs outage time, constant peak load; dashed = converter brownout threshold. Ideal capacitor energy model only. Inrush is an entered bound, not predicted waveform. No battery is assumed, and host heater/RF demand remains separate from the payload branch. These checks do not add a second power gate to the mission solver.</p><p class="small-note">Next evidence: detailed CAD + tolerances/cable routing; selected motor/gear/encoder; host ICD voltage/current/inrush/thermal contacts; installed antenna EM/VNA/3D pattern; launch vibration + landing shock + thermal-vacuum/thermal-cycle tests; absolute attitude/LOS and fault-injection bench tests.</p></div></article>`;
let cachedConfig,cached;
export function designStudy(c,r){if(cachedConfig!==c||cached?.result!==r){const assembly=assemblyStudy(c);cached={result:r,assembly,electrical:electricalStudy(c,r),alternatives:[80,70,60,50.8].map(size=>{const s=assemblyStudy({...c,antennaWidthMm:size,antennaHeightMm:size},10);return {plateMm:size,sampledPassPercent:s.sampledPassPercent,allSampledFit:s.allSampledFit};})};cachedConfig=c;}return cached;}
export function exportDesign(c,r){const d=designStudy(c,r);return {modelVersion:r.modelVersion,config:c,geometryBasis:'Photo-proportion lander / concept component allocations; not CAD or ECAD',assembly:d.assembly,electrical:d.electrical,alternatives:d.alternatives,warning:'Changing plate size is a packaging comparison, not a validated antenna redesign. RF performance must be re-established.'};}
export function renderDesign(c,r){
  const d=designStudy(c,r),a=d.assembly,e=d.electrical;
  $('#design-fit-summary').innerHTML=`<p class="orange-text"><b>${a.allSampledFit?'SAMPLED FIT ONLY — HARDWARE UNVERIFIED':'FULL REQUESTED TRAVEL NOT VERIFIED / INTERFERENCE FOUND'}</b></p><p>Plate diagonal <b>${f(a.plateDiagonalMm,2)} mm</b> · usable horizontal cavity <b>${f(a.internalSideMm,1)} mm</b> · vertical cavity ${f(a.internalCavityHeightMm,1)} mm. Sampled assembly fit ${f(a.sampledPassPercent,1)}% at ${a.stepDeg}° spacing. Worst signed clearance ${f(a.minimumClearanceMm,2)} mm.</p><p>Square-plate bound for unrestricted orientation inside the available cavity ≈${f(a.unrestrictedSquarePlateBoundMm,1)} mm per side <b>before motor/yoke/cable allowances</b>. A fixed 80 mm board may fit; rotating the full mechanism is a different requirement.</p>`;
  $('#design-size-comparison').innerHTML=`<table><thead><tr><th>Square plate</th><th>10° sampled fit</th><th>RF consequence</th></tr></thead><tbody>${d.alternatives.map(v=>`<tr><td>${v.plateMm} × ${v.plateMm} mm</td><td>${f(v.sampledPassPercent,1)}%</td><td>${v.plateMm===80?'Reference dimensions only':'New antenna design / EM + measurements required'}</td></tr>`).join('')}</tbody></table>`;
  $('#design-bus-summary').innerHTML=`<p><b>Payload source: lander bus; no onboard battery / heater</b></p><p>Peak simulated payload branch ${f(e.peakLoadW,2)} W · minimum host bus ${c.busMinV} V → load terminal ${f(e.loadedV,2)} V · current ${f(e.steadyA,3)} A. Budget ${c.busCurrentLimitA} A; entered inrush ${c.inrushA} A for ${c.inrushMs} ms: <b class="${e.currentPass?'green-text':'orange-text'}">${e.currentPass?'WITHIN CURRENT ALLOCATION':'CURRENT / INRUSH EXCEEDS ALLOCATION'}</b>.</p><p>${c.holdCapUf} µF input capacitance → ideal hold-up ${f(e.holdUpMs,1)} ms before ${c.brownoutV} V; requested interruption ${c.outageMs} ms: <b>${e.outagePass?'WITHIN IDEAL HOLD-UP':'BROWNOUT EXPECTED'}</b>. ${e.voltagePass?'Steady terminal voltage above threshold.':'Steady voltage fails / constant-power solution collapses.'}</p>`;
  lineChart($('#hold-up-chart'),[{color:'#43d5d5',data:e.rows}],{xunit:' ms',xmax:Math.max(c.outageMs,100),threshold:c.brownoutV,ymin:0});
  const canvas=$('#assembly-map'),width=Math.round(canvas.getBoundingClientRect().width);if(width){canvas.width=width;canvas.height=280;const ctx=canvas.getContext('2d'),p=36,nx=a.azValues.length,ny=a.elValues.length,cw=(width-2*p)/nx,ch=208/ny;
    for(const [i,row] of a.rows.entries()){ctx.fillStyle=row.pass?'#7abc77':'#9b5149';ctx.fillRect(p+(i%nx)*cw,p+(ny-1-Math.floor(i/nx))*ch,Math.ceil(cw),Math.ceil(ch));}
    ctx.fillStyle='#c8d3d8';ctx.font='11px sans-serif';ctx.textAlign='center';for(let i=0;i<5;i++){ctx.fillText(`${f(-c.azLimit+i*c.azLimit/2,0)}°`,p+i*(width-2*p)/4,268);ctx.fillText(`${f(c.elMax-i*(c.elMax-c.elMin)/4,0)}°`,17,p+i*208/4+4);}
  }
}
export function renderDesignFrame(c,frame){const a=assemblyFit(c,frame.az*180/Math.PI,frame.el*180/Math.PI);$('#design-current').innerHTML=`<p><b>Current concept assembly: ${a.fits?'FITS PROXIES':'DOES NOT FIT / CABLE LIMIT'}</b> · clearance ${f(a.minClearanceMm)} mm · ${a.failures.map(x=>`${x.part} (${f(x.clearanceMm)} mm)`).join('; ')||'no proxy interference'}${a.cablePass?'':'; cable twist allocation exceeded'}</p>`;}
export function designReport(c,r){const d=designStudy(c,r);return `\n## 2U assembly and host bus screening\n3 concept PCBs, no local battery/heater. Assembly grid step ${d.assembly.stepDeg} deg; sampled pass ${f(d.assembly.sampledPassPercent,2)}%; minimum signed clearance ${f(d.assembly.minimumClearanceMm,2)} mm. This is not continuous CAD clearance or mission reliability. Plate-only solver limits remain separate.\nWorst payload branch ${f(d.electrical.peakLoadW)} W; minimum terminal ${f(d.electrical.loadedV)} V; entered inrush ${c.inrushA} A; current allocation pass ${d.electrical.currentPass}; ideal capacitor hold-up ${f(d.electrical.holdUpMs)} ms; outage pass ${d.electrical.outagePass}. No circuit transient validation.\n`;
}
