import './style.css';
import {applyAntennaProfile,DEFAULTS,PRESETS,BOUNDS,MODEL_VERSION,presetConfig,validateConfig,runSimulation,runThermal,runStepResponse,antennaGain,patchEstimate,parsePatternCSV,csvExport} from './engine.js';
import {engineeringHTML,radioResearchHTML,referenceHTML,renderEngineering,engineeringReport} from './engineering-ui.js';
import {DEG} from './math.js';
import {MissionScene} from './scene.js';
import {lineChart,patternChart,scatterChart} from './charts.js';
import {RF_LAB_HTML,RFLab} from './rf-lab.js';
import {SURFACE,surfaceAssessment,surfaceHTML,renderSurface} from './surface-payload.js';
import {designHTML,renderDesign,renderDesignFrame,exportDesign} from './design-ui.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={play:'M8 5v14l11-7z',pause:'M8 5v14M16 5v14',reset:'M3 10a9 9 0 1 1 2 9M3 4v6h6',download:'M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5',layers:'m12 3 10 6-10 6L2 9zM2 14l10 6 10-6',orbit:'M21 12a9 9 0 1 1-9-9M16 3h5v5M21 3l-9 9',antenna:'m4 4 16 16M5 5a9 9 0 0 0 12 12M9 9a4 4 0 0 0 5 5M15 3a6 6 0 0 1 6 6M15 7a2 2 0 0 1 2 2M9 16l-3 5M6 21h9',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',arrow:'M5 12h14m-5-5 5 5-5 5',check:'m5 12 4 4L19 6',info:'M12 11v6M12 7v.1M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',close:'m6 6 12 12M6 18 18 6',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 1v3M12 20v3M1 12h3M20 12h3M4 4l2 2M18 18l2 2M4 20l2-2M18 6l2-2',chart:'M4 3v17h17M7 15l4-5 4 2 6-7',file:'M14 2H5v20h14V7zM14 2v6h5M8 12h8M8 16h6',upload:'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5',camera:'M3 7h4l2-3h6l2 3h4v13H3zM16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0'};
const icon=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.orbit}"/></svg>`;
const fmt=(v,n=1)=>v===null||!Number.isFinite(v)?'—':v.toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n});
let config={...DEFAULTS};
try {const saved=localStorage.getItem('lunar-link-config-v1.2');if(saved) config=validateConfig(JSON.parse(saved));}catch{}
let result,scene,rfLab,tab='mission',time=0,playing=false,speed=1,activePreset=config.scenario,worker=null,batch=null,thermal=null,stepResult=null;
let provenance={};
const green='#cced9c',orange='#e9a278',blue='#8ab9e6';

// Field labels, units, increments and practical explanations are kept next to the UI.
const groups=[
  {name:'Landing dynamics',sub:'การเคลื่อนที่ของยาน',open:true,fields:[
    ['roll','Final roll','°',1,'การเอียงรอบแกน Z'],['pitch','Final pitch','°',1,'การเอียงรอบแกน X'],['yaw','Final yaw','°',1,'การหมุนรอบแกน Y'],
    ['jitter','Vibration amplitude','°',0.05,'การสั่นแบบไซน์หลัง touchdown'],['jitterHz','Vibration frequency','Hz',0.1],['rampTime','Tilt transition','s',0.1],['duration','Scenario duration','s',1],['eventTime','Touchdown at','s',0.5]
  ]},
  {name:'Communication target',sub:'ทิศเป้าหมายในกรอบท้องถิ่น',fields:[['targetAz','Target azimuth','°',1],['targetEl','Target elevation','°',1],['distanceKm','Slant range','km',100,'ค่าคงที่ในแต่ละ scenario; ไม่มี ephemeris'],['horizon','Terrain horizon','°',1]]},
  {name:'Gimbal & controller',sub:'กลไก มอเตอร์ และเซนเซอร์',fields:[
    ['azLimit','Azimuth limit ±','°',1],['elMin','Elevation minimum','°',1],['elMax','Elevation maximum','°',1],['speedLimit','Maximum speed','°/s',5],
    ['inertia','Inertia / axis','kg·m²',0.00001],['movingMass','Moving payload mass','kg',0.01],['cgOffset','CG from pivot','m',0.001],['torqueLimit','Torque limit / axis','N·m',0.001],
    ['kp','Proportional gain Kp','N·m/rad',0.001],['ki','Integral gain Ki','N·m/(rad·s)',0.001],['kd','Derivative gain Kd','N·m·s/rad',0.0001],
    ['friction','Coulomb friction','N·m',0.001],['damping','Viscous damping','N·m·s/rad',0.001],['controlHz','Controller frequency','Hz',10],['delayMs','Command delay','ms',1],
    ['encoderBits','Encoder resolution','bit',1],['sensorBias','Attitude bias','°',0.01],['sensorNoise','Uniform noise ±','°',0.005],['torqueConstant','Motor torque constant','N·m/A',0.01],['resistance','Equivalent winding R','Ω',0.1],['pointingRequirement','Pointing criterion','°',0.1]
  ]},
  {name:'Radio & antenna',sub:'RF link budget · ค่าสมมติฐาน',fields:[
    ['frequencyGHz','Frequency','GHz',0.001],['txPowerW','RF output power','W',0.5],['peakGain','Boresight gain','dBi',0.5],['beamwidth','Full −3 dB beamwidth','°',1],['receiverGT','Receiver G/T','dB/K',0.5],
    ['bitrateKbps','Bit rate','kbps',1],['requiredEbNo','Required Eb/N₀','dB',0.1],['implementationLoss','Implementation loss','dB',0.1],['reserveDb','Required link reserve','dB',0.1],['cableLoss','TX cable loss','dB',0.1],['polLoss','Polarization loss','dB',0.1],['otherLoss','Other propagation loss','dB',0.1]
  ]},
  {name:'Lunar environment',sub:'Thermal · regolith · shock',fields:[
    ['initialTemp','Initial actuator temperature','°C',1],['baseTemp','Initial lander temperature','°C',1],['groundTemp','Ground temperature','°C',1],['sunlight','Solar illumination','0–1',0.05],['solarIncidence','Solar incidence cosine','0–1',0.05],
    ['emissivity','IR emissivity','ε',0.05],['absorptivity','Solar absorptivity','α',0.05],['thermalArea','Radiating area','m²',0.001],['heatCapacity','Thermal capacitance','J/K',10],['conductance','Mount conductance','W/K',0.01],['groundView','Ground view factor','0–1',0.05],
    ['heaterW','Lander heater','W',0.5],['heaterSetpoint','Heater setpoint','°C',1],['operatingMin','Motor operating minimum','°C',1],['operatingMax','Motor operating maximum','°C',1],
    ['dust','Dust exposure index','0–1',0.05,'สมมติฐาน sensitivity ไม่ใช่ปริมาณฝุ่นที่วัดได้'],['sealFactor','Dust transmission factor','0–1',0.05,'0 = ป้องกันทั้งหมดตามสมมติฐาน, 1 = ไม่ลดผลฝุ่น'],['shockG','Touchdown acceleration','g₀',1,'g₀ = 9.80665 m/s²; ไม่ใช่ lunar g'],['shockMs','Half-sine pulse length','ms',5]
  ]},
  {name:'Power & reproducibility',sub:'พลังงานและการทำซ้ำผล',fields:[['batteryWh','Payload energy allocation','Wh',1],['electronicsW','Electronics power','W',0.1],['rfEfficiency','PA efficiency','0–1',0.05],['seed','Random seed','',1]]}
];
groups[0].fields.push(['jitterDuration','Vibration duration','s',0.1],['jitterDecay','Vibration decay time','s',0.1],['restRate','Rest rate threshold','°/s',0.1],['restHold','Rest confirmation time','s',0.1],['landingLock','Landing lock (1=on)','0/1',1]);
groups.push({name:'2U envelope & mounting',sub:'Payload รวมเสาและ gimbal ภายใน 2U',fields:[['antennaWidthMm','Antenna width','mm',1],['antennaHeightMm','Antenna height','mm',1],['antennaThicknessMm','Antenna thickness','mm',0.01],['antennaMassG','Antenna reference mass','g',1,'ไม่ใช่มวลรวม: moving mass และ inertia ต้องมาจาก CAD'],['clearanceMm','Plate clearance allowance','mm',0.1],['mountX','Mount X on lander','m',0.01],['mountY','Mount Y on lander','m',0.01],['mountZ','Mount Z on lander','m',0.01],['burialDepth','Ground penetration','m',0.01]]});
groups.push({name:'Surface payload interface',sub:'Top green zone · total mass ≤1.5 kg',fields:[['payloadMassKg','Total delivered payload mass','kg',0.01,'รวมเสา gimbal โครง อิเล็กทรอนิกส์ สาย และอะแดปเตอร์; 1.5 kg เป็นขอบบนที่ทีมระบุ ไม่ใช่ผลชั่ง']]});
groups.push({name:'Assembly & host bus screening',sub:'พื้นที่กลไก สาย RF และไฟจาก lander',fields:[['wallMm','Wall thickness allowance','mm',0.1],['pitchMotorWidthMm','Pitch motor outward width','mm',0.5,'ขนาดสมมติของ motor proxy; ต้องเลือกชิ้นส่วนจริง'],['rfBendRadiusMm','RF cable bend-space radius','mm',0.5,'keep-out sphere โดยประมาณ ไม่ใช่ cable stress model'],['cableTwistLimitDeg','Cable twist allocation ±','°',5],['busMinV','Minimum host bus','V',0.5],['busMaxV','Maximum host bus','V',0.5,'ใช้กำหนดช่วง ICD; ยังไม่มี switching / overvoltage model'],['busCurrentLimitA','Payload branch current allocation','A',0.05],['harnessOhm','Harness round-trip resistance','Ω',0.05],['inrushA','Entered turn-on current bound','A',0.1],['inrushMs','Entered turn-on duration','ms',1],['holdCapUf','Input hold-up capacitance','µF',10],['brownoutV','Converter brownout threshold','V',0.5],['outageMs','Requested host interruption','ms',10]]});
groups.push({name:'Lander thermal & power interface',sub:'Heater อยู่ที่ lander',fields:[['landerHeatCapacity','Lander thermal capacitance','J/K',100],['landerArea','Lander radiating area','m²',0.01],['landerEmissivity','Lander IR emissivity','',0.01],['landerAbsorptivity','Lander solar absorptivity','',0.01],['landerBatteryWh','Host allocated energy','Wh',10],['heaterConnected','Thermal contact (1=intact)','0/1',1],['hostPower','Host power after landing (1=on)','0/1',1],['hostRadio','RF supply (1=host, 0=payload)','0/1',1],['busVoltage','Payload bus voltage','V',1],['regulatorEfficiency','Payload regulator efficiency','0–1',0.01]]});
groups.push({name:'Antenna RF detail',sub:'Pattern, matching, polarization, receiver',fields:[['beamwidthV','Second-plane HPBW','°',1,'ใช้เมื่อเลือก Two-plane cosine; ไม่ใช่ measured pattern'],['backlobeFloorDb','Relative pattern floor','dB',1],['s11Db','Scalar S11','dB',0.1,'ค่าคงที่สมมติ จนกว่าจะ import frequency response'],['axialRatioDb','Scalar axial ratio','dB',0.1],['installationLossDb','Additional installation loss','dB',0.1,'อย่าหักซ้ำหาก imported pattern วัดแบบ mounted แล้ว'],['receiverTempK','Receiver system temperature','K',1,'ใช้แยก received/noise power; G/T เป็น input หลักของ margin'],['receiverBandwidthKHz','Receiver noise bandwidth','kHz',1],['codingRate','Information / coded bit rate','',0.05],['modulationBits','Bits per symbol','',1],['rolloff','Pulse-shaping roll-off','',0.05],['rfTempCoeffPpm','Resonance shift coefficient','ppm/°C',1,'ใช้ shift frequency lookup เมื่อ import response; ไม่ใช่ coefficient จาก paper'],['rfReferenceTemp','RF reference temperature','°C',1]]});
function fieldHTML([key,label,unit,step,hint]) {const [min,max]=BOUNDS[key];const range=['roll','pitch','yaw','jitter','targetEl','dust','sunlight'].includes(key);return `<div class="field"><label for="p-${key}">${label}<span>${unit}</span></label><div class="field-entry">${range?`<input type="range" aria-label="${label} slider" data-range="${key}" min="${min}" max="${max}" step="${step}" value="${config[key]}">`:''}<input id="p-${key}" type="number" data-param="${key}" min="${min}" max="${max}" step="${step}" value="${config[key]}" aria-label="${label}" title="${hint||label}"></div>${hint?`<small>${hint}</small>`:''}</div>`;}

$('#app').innerHTML=`
  <header class="topbar">
    <a class="brand" href="#" aria-label="Lunar Link home"><span class="brand-mark">${icon('antenna',23)}</span><span>LUNAR<span class="brand-light">LINK</span><small>MISSION ENGINEERING STUDIO</small></span></a>
    <div class="project-label"><span class="tiny-moon"></span> SURFACE COMMUNICATIONS <span class="slash">/</span> LUNAR LANDER</div>
    <div class="top-actions"><span class="model-badge"><i></i> Engineering model · v${MODEL_VERSION}</span><button class="button ghost" id="import-config">${icon('upload')}<span>Import</span></button><details class="export-menu"><summary class="button">${icon('download')}<span>Export run</span></summary><div class="menu"><button data-export="csv">Telemetry CSV</button><button data-export="json">Scenario + results JSON</button><button data-export="report">Engineering report .md</button><button data-export="png">3D view PNG</button></div></details></div>
  </header>
  <div class="workspace">
    <aside class="sidebar"><div class="sidebar-title"><span>${icon('settings')} Scenario configuration</span><button id="reset-config" class="icon-button" title="Restore selected preset" aria-label="Restore selected preset">${icon('reset',15)}</button></div>
      <div class="sidebar-scroll"><div class="scenario-label">MISSION PROFILE <span>${Object.keys(PRESETS).length} PRESETS</span></div><div class="presets">${Object.entries(PRESETS).map(([id,p],i)=>`<button class="preset ${id===activePreset?'active':''}" data-preset="${id}" title="${p.thai}"><span class="preset-number">${String(i+1).padStart(2,'0')}</span><span>${p.label}</span><span class="preset-dot"></span></button>`).join('')}</div>
      <p id="preset-note" class="preset-note">${PRESETS[activePreset].note}</p>
      ${groups.map((g,i)=>`<details class="control-group" ${g.open?'open':''}><summary><span><b>${g.name}</b><small>${g.sub}</small></span><span class="chevron">⌄</span></summary><div class="group-fields">${g.fields.map(fieldHTML).join('')}${i===2?`<div class="field"><label for="jam-axis">Fault at touchdown</label><select id="jam-axis"><option value="none">No fault</option><option value="azimuth">Azimuth jam</option><option value="elevation">Elevation jam</option></select></div>`:''}</div></details>`).join('')}
      <div class="assumption-note">${icon('info',16)}<span>ค่าตั้งต้นเป็นสมมติฐานสำหรับออกแบบ<br>เปลี่ยนเป็นสเปกจริงก่อนใช้ยืนยันสมรรถนะ</span></div></div>
      <div class="sidebar-bottom"><span id="config-state"><i></i> All changes calculated</span><button id="run" class="button primary">${icon('play',15)} Run scenario</button></div>
    </aside>
    <main>
      <div class="page-heading"><div><div class="eyebrow">ULTRA SMOOTH LANDING <span> / </span> SIMULATION WORKBENCH</div><h1>Recover the link. <span>Know the limits.</span></h1><p>Explore antenna pointing, communication margin and lunar environment effects.</p></div><div class="session"><span class="live-dot"></span><span>LOCAL SIMULATION<small id="scenario-name">Off-nominal landing</small></span></div></div>
      <nav class="tabs" aria-label="Workbench sections">${[['mission','orbit','Mission overview'],['radio','antenna','Antenna & RF'],['environment','sun','Environment'],['analysis','chart','Batch analysis'],['evidence','file','Model & evidence']].map(([id,ic,label])=>`<button class="tab ${id==='mission'?'active':''}" data-tab="${id}" aria-selected="${id==='mission'}">${icon(ic,16)}${label}</button>`).join('')}</nav>
      <section id="panel-mission" class="tab-panel">
        <div class="metric-row">
          <article class="metric"><div class="metric-label">GIMBAL LINK MARGIN <span class="tag green">TRACKED</span></div><div class="metric-value lime" id="metric-margin">— <small>dB</small></div><div class="metric-foot" id="margin-foot">Required reserve ≥ 3.0 dB</div></article>
          <article class="metric"><div class="metric-label">POINTING ERROR ${icon('orbit',15)}</div><div class="metric-value" id="metric-error">— <small>°</small></div><div class="metric-foot" id="error-foot">Target ≤ 0.5°</div></article>
          <article class="metric"><div class="metric-label">FIXED ANTENNA <span class="tag orange">BASELINE</span></div><div class="metric-value amber" id="metric-fixed">— <small>dB</small></div><div class="metric-foot" id="fixed-foot">Same RF hardware & starting alignment</div></article>
          <article class="metric"><div class="metric-label">GIMBAL LINK AVAILABILITY ${icon('chart',15)}</div><div class="metric-value" id="metric-availability">— <small>%</small></div><div class="metric-foot" id="availability-foot">Across the complete scenario</div></article>
        </div>
        <div class="simulation-row">
          <article class="card viewport-card"><div class="card-heading"><div><span class="section-index">01</span><h2>Lunar surface · 3D viewport</h2></div><span class="subtle">Y-up local frame</span></div>
            <div class="scene-wrap"><div id="scene"></div><div class="scene-top"><span class="scene-live" id="scene-state"><i></i> READY</span><span class="scene-tag">ISPACE PHOTO CONCEPT · NOT CAD</span></div>
            <div class="scene-views"><button class="view-button active" data-view="orbit" title="Free orbit / isometric-style view">Isometric</button><button class="view-button" data-view="front">Side</button><button class="view-button" data-view="top">Top</button><button class="view-button" data-view="underside">Bottom</button><button class="view-button" data-view="mount">Mount</button><button class="view-button" data-view="detail">Payload 2U</button></div>
            <div class="scene-overlays"><label><input id="studio-view" type="checkbox"> White studio</label><label><input id="show-beam" type="checkbox"> Radiation lobe</label><label><input id="explode" type="checkbox"> Exploded view</label><label><input id="payload-cover" type="checkbox" checked> Payload cover</label><label><input id="show-zones" type="checkbox" checked> Brochure payloads · visual only</label></div>
            <div class="scene-legend"><span><i class="dot blue"></i>Target LOS</span><span><i class="dot green"></i>Gimbal boresight</span><span><i class="dot orange"></i>Fixed boresight</span></div>
            <div class="scene-help">Drag to orbit · Scroll to zoom <span id="pose-label">ROLL 0° &nbsp; PITCH 0° &nbsp; YAW 0°</span></div></div>
            <div class="model-key"><span><i style="background:#ef2439"></i>Orbiter</span><span><i style="background:#70e138"></i>Top surface</span><span><i style="background:#345de5"></i><i style="background:#dedb29"></i>Bottom surface</span><span><i style="background:#14babf"></i>Our 2U</span><button class="button" id="export-model">Download 3D .glb</button><small>Photo reconstruction. Coloured service blocks are visual allocations; they are not included in mass, contact or RF obstruction calculations.</small></div>
            <div class="playback"><button id="play" class="play-button" aria-label="Play simulation">${icon('play',17)}</button><button id="rewind" class="icon-button" aria-label="Rewind simulation">${icon('reset',17)}</button><span id="clock" class="clock">00.00 <small>/ 18.00 s</small></span><input id="timeline" type="range" min="0" max="18" step="0.02" value="0" aria-label="Simulation timeline"><select id="speed" aria-label="Playback speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option></select></div>
          </article>
          <article class="card inspector"><div class="card-heading"><div><span class="section-index">02</span><h2>System telemetry</h2></div><span class="status-pill" id="system-status">NOMINAL</span></div><div class="inspector-body">
            <div class="telemetry-title">GIMBAL POSITION <span>ACTUAL / COMMAND</span></div><div class="angle-row"><span>Azimuth</span><b id="az-actual">—</b><small id="az-command">—</small></div><div class="axis-track"><i id="az-bar"></i></div><div class="angle-row"><span>Elevation</span><b id="el-actual">—</b><small id="el-command">—</small></div><div class="axis-track"><i id="el-bar"></i></div>
            <dl class="telemetry-list"><div><dt>Actuator temperature</dt><dd id="live-temp">—</dd></div><div><dt>Electrical draw</dt><dd id="live-power">—</dd></div><div><dt>Energy used</dt><dd id="live-energy">—</dd></div><div><dt>Az / El torque</dt><dd id="live-torque">—</dd></div><div><dt>Target in travel</dt><dd id="live-reachable">—</dd></div><div><dt>Line of sight</dt><dd id="live-los">—</dd></div></dl>
            <div class="insight" id="insight"><span class="insight-icon">${icon('info',17)}</span><div><b>Both antennas start aligned</b><p>The same scenario and RF assumptions are used for both systems.</p></div></div>
            <div class="inspector-footer"><span>Integration</span><b>2 ms</b><span>Controller</span><b id="control-rate">100 Hz</b></div>
          </div></article>
        </div>
        ${surfaceHTML}${engineeringHTML}${designHTML}<div class="chart-row"><article class="card"><div class="card-heading"><div><span class="section-index">03</span><h2>Pointing accuracy</h2><span class="unit">deg</span></div><div class="chart-legend"><span class="green-text">● Gimbal</span><span class="orange-text">● Fixed</span></div></div><canvas id="error-chart" class="chart" role="img" aria-label="Pointing error over the full scenario"></canvas><div class="chart-footer"><span id="rms-caption">RMS error —</span><span>Dashed line = pointing criterion</span></div></article>
        <article class="card"><div class="card-heading"><div><span class="section-index">04</span><h2>Communication margin</h2><span class="unit">dB</span></div><div class="chart-legend"><span class="green-text">● Gimbal</span><span class="orange-text">● Fixed</span></div></div><canvas id="margin-chart" class="chart" role="img" aria-label="Link margin compared to required reserve"></canvas><div class="chart-footer"><span>Gaps = blocked or unpowered</span><span id="margin-caption">Reserve ≥ 3 dB</span></div></article></div>
      </section>
      <section id="panel-radio" class="tab-panel" hidden>${RF_LAB_HTML}${radioResearchHTML}
        <div class="section-intro"><div><h2>From pointing to a usable link.</h2><p>Both antennas use the same pattern, RF power and receiver. Directional gain is applied once.</p></div><span class="tag">END-OF-RUN VALUES</span></div>
        <div class="two-column"><article class="card"><div class="card-heading"><h2>Antenna radiation pattern</h2><span id="pattern-source" class="tag green">ASSUMED COSINE MODEL</span></div><canvas id="pattern-chart" class="pattern-chart" role="img" aria-label="Antenna relative gain polar plot"></canvas><div class="card-padding"><p class="muted">Legacy φ=0° polar cut · 0° is boresight · radial scale relative to on-axis gain. Use the 3D lab above for asymmetric patterns.</p><div class="button-row"><button id="import-pattern" class="button">${icon('upload',15)} Import pattern CSV</button><button id="clear-pattern" class="button ghost">Use analytical model</button></div><p class="small-note">CSV: angle_deg,gain_dbi · unique angles spanning 0–180°. A single polar cut is revolved about boresight; asymmetric 3D patterns are not represented.</p></div></article>
        <article class="card"><div class="card-heading"><h2>Link budget</h2><span class="unit">Gimbal / Fixed</span></div><div id="budget-table" class="card-padding"></div><div class="formula-note">C/N₀ = EIRP − FSPL + G/T + 228.599 − losses<br>Margin = C/N₀ − 10 log₁₀(Rb) − required Eb/N₀ − implementation loss</div></article></div>
        <article class="card patch-card"><div><span class="eyebrow">RECTANGULAR PATCH · FIRST-PASS SIZING</span><h2>Start with a physical antenna.</h2><p class="muted">Transmission-line estimate of the fundamental mode. This calculator does not predict S11, efficiency, array coupling or flight performance.</p></div><div class="patch-inputs"><label>Frequency (GHz)<input id="patch-f" type="number" min="0.1" max="40" step="0.001" value="2.205"></label><label>Dielectric constant εr<input id="patch-er" type="number" min="1.01" max="30" step="0.01" value="6.4"></label><label>Substrate thickness (mm)<input id="patch-h" type="number" min="0.01" max="10" step="0.01" value="1.52"></label></div><div id="patch-result" class="patch-result"></div><p class="small-note patch-disclaimer">Single-layer patch sizing is independent of the stacked CP reference antenna and illustrative viewport. It does not reproduce the paper design. Import verified pattern data to connect a real design to this simulation.</p></article>
      </section>
      <section id="panel-environment" class="tab-panel" hidden>
        <div class="section-intro"><div><h2>Design for the surface.</h2><p>Evaluate actuator thermal response, dust sensitivity and a touchdown load pulse.</p></div></div>
        <div class="three-column"><article class="card env-card"><span class="eyebrow">REGOLITH</span><h2 id="dust-factor">1.00×</h2><span>Assumed friction multiplier from dust</span><p>1 + 8 × exposure × seal transmission. A sensitivity law, not a calibrated ingress model. Cold friction is applied separately.</p></article><article class="card env-card"><span class="eyebrow">TOUCHDOWN SHOCK</span><h2 id="shock-load">0.00 N</h2><span>Peak inertial force on moving payload</span><p>F = mass × peak g₀ × 9.80665. The half-sine pulse enters the pivot torque calculation. This is not an FEA stress or shock qualification result.</p></article><article class="card env-card"><span class="eyebrow">COLD SURVIVAL</span><h2 id="heater-rating">3.0 W</h2><span>Thermostatic lander heater capacity</span><p>±1°C hysteresis around the setpoint. Heater warms the lander node; contact conductance transfers heat to the payload. No active cooler is modeled.</p></article></div>
        <article class="card"><div class="card-heading"><h2>Long-duration thermal study</h2><div class="button-row"><label class="inline-label">Duration <select id="thermal-hours"><option value="6">6 hours</option><option value="24" selected>24 hours</option><option value="72">72 hours</option><option value="336">336 hours</option></select></label><button id="run-thermal" class="button primary">${icon('play',14)} Run thermal study</button></div></div><div class="thermal-results" id="thermal-results">Run a separate survival-mode study with the current environment and battery settings.</div><canvas id="thermal-chart" class="chart tall" role="img" aria-label="Actuator temperature during thermal study"></canvas><div class="formula-note">Survival mode: RF and motors OFF; electronics and lander heater draw from their allocated energy budgets. Constant illumination and ground boundary. Two thermal nodes: payload (blue), lander (orange). Heater is on the lander; payload receives heat through conduction. Host and payload energy allocations can expire separately.</div></article>
        <div class="chart-row"><article class="card"><div class="card-heading"><h2>Motor torque · scenario</h2><span class="unit">N·m</span></div><canvas id="torque-chart" class="chart" role="img" aria-label="Azimuth and elevation torque"></canvas></article><article class="card"><div class="card-heading"><h2>Electrical power · scenario</h2><span class="unit">W</span></div><canvas id="power-chart" class="chart" role="img" aria-label="Total gimbal-system power over time"></canvas></article></div>
      </section>
      <section id="panel-analysis" class="tab-panel" hidden>
        <div class="section-intro"><div><h2>Find the operating envelope.</h2><p>Reproducible Monte Carlo analysis under declared distributions. These are scenario pass rates, not mission reliability predictions.</p></div></div>
        <article class="card step-study"><div class="card-heading"><h2>Controller step-response test</h2><div class="button-row"><label class="inline-label">Azimuth step <input id="step-angle" type="number" min="0.1" max="30" step="0.1" value="5" aria-label="Azimuth step amplitude"> °</label><button id="run-step" class="button primary">${icon('play',14)} Measure motor settling</button></div></div><div id="step-results" class="thermal-results">A separate static-base test measures azimuth settling within the configured pointing band.</div><canvas id="step-chart" class="chart" role="img" aria-label="Azimuth error after a commanded step"></canvas><div class="formula-note">Base stationary; vibration, shock and injected jam OFF. Current controller, sensor, motor, temperature and power settings retained. Start at target azimuth minus the selected step; hold target for 5 s. Settling requires remaining inside the band for the rest of the observation. This is a model test, not bench validation.</div></article>
        <article class="card batch-controls"><div><h2>Landing uncertainty sweep</h2><p class="muted">Uniform Euler-angle distributions: roll ±180°, pitch ±180°, yaw ±180°, attitude bias ±0.3°, dust 0–1.<br>All other parameters stay at the current configuration. Success = link reserve met for ≥95% of samples after vibration window + rest hold + 2 s acquisition allowance.</p></div><div class="button-row"><label class="inline-label">Trials<select id="batch-count"><option value="50">50</option><option value="100" selected>100</option><option value="250">250</option><option value="1000">1,000</option></select></label><button id="run-batch" class="button primary">${icon('play',15)} Run analysis</button><button id="cancel-batch" class="button ghost" hidden>Cancel</button></div></article>
        <div id="batch-progress" class="progress-track" hidden><i></i></div><p id="batch-status" class="muted">No batch has been run. Seed and sampled inputs are saved with every export.</p>
        <div class="two-column"><article class="card"><div class="card-heading"><h2>Landing attitude map</h2><span class="unit">pitch / roll</span></div><canvas id="batch-chart" class="chart tall" role="img" aria-label="Monte Carlo outcomes by landing roll and pitch"></canvas><div class="chart-footer"><span class="green-text">● Gimbal passed</span><span class="orange-text">● Gimbal failed</span></div></article><article class="card"><div class="card-heading"><h2>Results & uncertainty</h2><button id="export-batch" class="button ghost" disabled>${icon('download',15)} CSV</button></div><div id="batch-results" class="card-padding empty-state">Run an analysis to compare fixed and gimballed antennas.<p>Each trial uses the same sampled conditions for both systems.</p></div></article></div>
      </section>
      <section id="panel-evidence" class="tab-panel" hidden>${referenceHTML}
        <div class="section-intro"><div><h2>Make every result reviewable.</h2><p>Model assumptions, requirements and numerical evidence travel with your exported run.</p></div><button id="export-report" class="button">${icon('file',15)} Export report</button></div>
        <article class="card"><div class="card-heading"><h2>Requirement assessment</h2><span class="tag">FULL SCENARIO</span></div><div id="requirements" class="card-padding"></div></article>
        <div class="two-column"><article class="card"><div class="card-heading"><h2>What is actually modeled</h2></div><div class="prose card-padding"><p><b>Pointing:</b> quaternion attitude; local Y up; +Z forward; azimuth about +Y; elevation about rotated −X. Target LOS and range remain constant during a run.</p><p><b>Actuation:</b> two independent rotary inertias, PID with conditional integration, encoder quantization, seeded uniform attitude noise, command delay, Coulomb/viscous friction, torque/speed limits, gravity from an offset payload and an imposed half-sine load pulse.</p><p><b>Communication:</b> axisymmetric gain model or imported polar cut, FSPL, receiver G/T, fixed polarization/other losses and Eb/N₀ threshold. A link passes only with the configured reserve. Data volume is an ideal scheduled-bit estimate, without packet or acquisition modeling.</p><p><b>Environment:</b> separate lander and payload thermal nodes, lander heater, allocated energy depletion and an explicitly assumed dust–friction law.</p></div></article>
        <article class="card"><div class="card-heading"><h2>Boundaries of the evidence</h2></div><div class="prose card-padding"><p>The 3D lander, equipment panels and compact patch antenna are procedural concept geometry, not imported CAD. Moving mass and inertia are user inputs, not measured from this mesh.</p><p>Hull obstruction uses a single body-aligned box; terrain uses a horizon mask and a ground-contact plane. Known attitude is an input; star-tracker/IMU estimation is not implemented. Detailed self-shadowing, terrain ray tracing, flexible structures, coupled multibody/base inertial dynamics, radiation damage and ephemerides are not solved.</p><p>Patch dimensions are preliminary estimates. No full-wave S11/VSWR, structural stress/FEA, seal performance or flight qualification is generated.</p><p>Pointing error comes directly from the trajectory. We do not add an RSS error budget on top of already simulated errors. Peak gain is not reduced a second time by pointing loss.</p><p>The 50 ms proposal response is assessed as configured sampling plus command delay only. Physical motor settling is measured separately; sensor acquisition and computation time need bench measurements.</p></div></article></div>
        <article class="card"><div class="card-heading"><h2>Reference basis & next validation</h2></div><div class="prose card-padding"><p><a href="https://www.mathworks.com/help/satcom/gs/satellite-link-budget.html" target="_blank" rel="noreferrer">MathWorks — Satellite link budget</a> · <a href="https://www.nasa.gov/smallsat-institute/sst-soa/thermal-control/" target="_blank" rel="noreferrer">NASA — Thermal control</a> · <a href="https://ntrs.nasa.gov/citations/20220018746" target="_blank" rel="noreferrer">NASA — Lunar dust mitigation guide</a></p><p>For competition evidence: replace inputs with traceable datasheets, import a measured or EM-solved antenna pattern, compare the controller to a bench step response, and use CAD-derived inertia plus independently verified thermal/structural models. Save the scenario JSON, telemetry CSV and report together.</p><p><b>Statistical interpretation:</b> Monte Carlo confidence intervals describe the chosen synthetic distributions only. They do not establish flight reliability. Defaults and presets are illustrative assumptions.</p></div></article>
      </section>
      <footer class="page-footer"><span><i></i> Runs locally · No external services at runtime</span><span>Engineering study · Assumptions are editable and exportable</span></footer>
    </main>
  </div><div id="toast" role="status" aria-live="polite"></div><input id="file-config" type="file" accept=".json,application/json" hidden><input id="file-pattern" type="file" accept=".csv,text/csv" hidden>`;

function toast(message,error=false) {const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),5500);}
function download(name,contents,type='text/plain') {const blob=new Blob([contents],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function populate(){for(const el of $$('[data-param]'))el.value=config[el.dataset.param];for(const el of $$('[data-range]'))el.value=config[el.dataset.range];$('#jam-axis').value=config.jamAxis;$$('[data-preset]').forEach(el=>el.classList.toggle('active',el.dataset.preset===activePreset));$('#preset-note').textContent=PRESETS[config.scenario].note;}
function frameAt(t){let lo=0,hi=result.frames.length-1;while(hi-lo>1){const mid=(lo+hi)>>1;if(result.frames[mid].t>t)hi=mid;else lo=mid;}return result.frames[Math.abs(result.frames[lo].t-t)<Math.abs(result.frames[hi].t-t)?lo:hi];}
function setPlaying(value){playing=value;$('#play').innerHTML=icon(playing?'pause':'play',17);$('#play').setAttribute('aria-label',playing?'Pause simulation':'Play simulation');}
let pendingTimer;
function invalidateAnalysis(){if(worker){worker.terminate();worker=null;$('#run-batch').disabled=false;$('#cancel-batch').hidden=true;$('#batch-progress').hidden=true;}batch=null;thermal=null;stepResult=null;$('#step-results').textContent='Run a step test for the current controller settings.';$('#batch-results').innerHTML='Configuration changed. Run the analysis with these inputs.';$('#batch-status').textContent='No current batch result.';$('#export-batch').disabled=true;$('#thermal-results').textContent='Run thermal study for the current configuration.';for(const id of ['#thermal-chart','#batch-chart','#step-chart']){const canvas=$(id);canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);}}
function recalculate(autoPlay=false){clearTimeout(pendingTimer);pendingTimer=null;try{config=validateConfig(config);result=runSimulation(config);time=0;setPlaying(autoPlay);$('#timeline').max=config.duration;$('#scenario-name').textContent=PRESETS[config.scenario].label;$('#config-state').innerHTML='<i></i> All changes calculated';$('#metric-availability').innerHTML=`${fmt(result.summary.availability,1)} <small>%</small>`;$('#availability-foot').textContent=`Fixed baseline ${fmt(result.summary.fixedAvailability,1)}% · full run`;$('#control-rate').textContent=`${config.controlHz} Hz`;$('#rms-caption').textContent=`Gimbal RMS ${fmt(result.summary.rmsError,2)}° · final 3 s ${fmt(result.summary.tailRms,2)}°`;$('#margin-caption').textContent=`Dashed line = ${fmt(config.reserveDb)} dB reserve`;try{localStorage.setItem('lunar-link-config-v1.2',JSON.stringify(config));}catch{}renderStatic();renderFrame();}catch(e){toast(e.message,true);}}
function editParam(key,value){try{config=validateConfig({...config,[key]:value});}catch(e){toast(e.message,true);populate();return;}if(['frequencyGHz','peakGain','beamwidth','antennaWidthMm','antennaHeightMm','antennaThicknessMm','antennaMassG'].includes(key))config.antennaProfile='custom';provenance[key]='User input; source not independently verified';const number=$(`[data-param="${key}"]`),range=$(`[data-range="${key}"]`);if(number)number.value=value;if(range)range.value=value;invalidateAnalysis();$('#config-state').textContent='Recalculating…';setPlaying(false);clearTimeout(pendingTimer);pendingTimer=setTimeout(()=>recalculate(false),150);}

function renderFrame(){if(!result)return;const f=frameAt(time);if(scene){scene.update(f,config);}
  $('#metric-margin').innerHTML=`${fmt(f.link.margin)} <small>dB</small>`;$('#metric-error').innerHTML=`${fmt(f.error,2)} <small>°</small>`;$('#metric-fixed').innerHTML=`${fmt(f.fixedLink.margin)} <small>dB</small>`;
  $('#margin-foot').textContent=f.link.available?`Link maintained · reserve ≥ ${fmt(config.reserveDb)} dB`:f.blocked?'Target blocked by horizon, ground or hull':!f.rfPowered?'RF power lost':!f.link.rf.supported?'Frequency outside imported RF data':!f.link.bandwidthPass?'Receiver bandwidth exceeded':`Below ${fmt(config.reserveDb)} dB required reserve`;
  $('#error-foot').textContent=`${f.error<=config.pointingRequirement?'Within':'Outside'} ${fmt(config.pointingRequirement,2)}° criterion`;
  $('#fixed-foot').textContent=`${f.fixedLink.available?'Link maintained':'Link unavailable'} · ${fmt(f.fixedError,1)}° mispointing`;
  $('#metric-margin').classList.toggle('bad',!f.link.available);$('#metric-error').classList.toggle('bad',f.error>config.pointingRequirement);
  $('#clock').innerHTML=`${time.toFixed(2).padStart(5,'0')} <small>/ ${config.duration.toFixed(2)} s</small>`;$('#timeline').value=time;
  $('#pose-label').textContent=`ROLL ${fmt(f.body.roll,0)}°   PITCH ${fmt(f.body.pitch,0)}°   YAW ${fmt(f.body.yaw,0)}°`;
  $('#az-actual').textContent=`${fmt(f.az*DEG,1)}°`;$('#el-actual').textContent=`${fmt(f.el*DEG,1)}°`;$('#az-command').textContent=`/ ${fmt(f.command[0]*DEG,1)}°`;$('#el-command').textContent=`/ ${fmt(f.command[1]*DEG,1)}°`;
  $('#az-bar').style.width=`${(f.az*DEG+config.azLimit)/(2*config.azLimit)*100}%`;$('#el-bar').style.width=`${(f.el*DEG-config.elMin)/(config.elMax-config.elMin)*100}%`;
  $('#live-temp').textContent=`${fmt(f.temp,1)} °C${f.heater?' · heater on':''}`;$('#live-power').textContent=`${fmt(f.power,2)} W`;$('#live-energy').textContent=`${fmt(f.energy,3)} / ${fmt(config.batteryWh,1)} Wh`;$('#live-torque').textContent=`${fmt(f.torque[0],3)} / ${fmt(f.torque[1],3)} N·m`;$('#live-reachable').textContent=f.reachable?'Reachable':'Travel / 2U limit';$('#live-los').textContent=f.blockedReason||'Clear';
  renderEngineering(config,result,f);
  renderDesignFrame(config,f);
  const status=f.locked?'LANDING LOCK':f.packagingLimited||!f.packaging.fits?'2U ENVELOPE LIMIT':!f.powered?'POWER LOST':f.jammed?'AXIS JAMMED':!f.motorOperational?'TEMP LIMIT':f.blocked?'OCCLUDED':!f.reachable?'TRAVEL LIMIT':f.error>config.pointingRequirement?'TRACKING':'ON TARGET';
  $('#system-status').textContent=status;$('#system-status').classList.toggle('warning',status!=='ON TARGET');$('#scene-state').innerHTML=`<i></i> ${playing?'SIMULATING':time>=config.duration?'COMPLETE':'PAUSED'} · T+${fmt(time,1)}s`;
  let title='Both antennas retain the link',note='The same RF assumptions are used for both systems.';
  if(f.link.available&&!f.fixedLink.available){title='Gimbal maintains communication';note='The fixed antenna is below the required reserve under this same disturbance.';}
  else if(!f.link.available){title=f.blocked?'No clear line of sight':!f.powered?'Energy budget exhausted':f.jammed?'An actuator is locked':'Communication requirement not met';note='This case is retained in the results. Change the design inputs to explore recovery.';}
  $('#insight b').textContent=title;$('#insight p').textContent=note;
  if(tab==='mission')drawMissionCharts();
}
function drawMissionCharts(){const x=result.frames;lineChart($('#error-chart'),[{color:orange,data:x.map(f=>({x:f.t,y:f.fixedError}))},{color:green,data:x.map(f=>({x:f.t,y:f.error}))}],{threshold:config.pointingRequirement,xmax:config.duration,event:config.eventTime,cursor:time});lineChart($('#margin-chart'),[{color:orange,data:x.map(f=>({x:f.t,y:f.fixedLink.margin}))},{color:green,data:x.map(f=>({x:f.t,y:f.link.margin}))}],{threshold:config.reserveDb,xmax:config.duration,event:config.eventTime,cursor:time});}
function table(rows,headers=['Quantity','Gimbal','Fixed']){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<${i?'td':'th'}>${v}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table>`;}
function renderStatic(){if(!result)return;const f=result.frames.at(-1),l=f.link,b=f.fixedLink,a=surfaceAssessment(config);renderSurface(config);if(tab==='mission')renderDesign(config,result);
  $('#budget-table').innerHTML=table([
    ['Antenna gain (dBi)',fmt(l.gain,2),fmt(b.gain,2)],['Pointing loss (dB)',fmt(l.pointingLoss,2),fmt(b.pointingLoss,2)],['EIRP (dBW)',fmt(l.eirp,2),fmt(b.eirp,2)],['Free-space loss (dB)',fmt(l.pathLoss,2),fmt(b.pathLoss,2)],['Receiver G/T (dB/K)',fmt(config.receiverGT),fmt(config.receiverGT)],['C/N₀ (dB-Hz)',f.blocked||!f.rfPowered?'—':fmt(l.cn0,2),b.margin===null?'—':fmt(b.cn0,2)],['Eb/N₀ (dB)',l.margin===null?'—':fmt(l.ebno,2),b.margin===null?'—':fmt(b.ebno,2)],['Link margin (dB)',`<b class="${l.available?'green-text':'orange-text'}">${fmt(l.margin,2)}</b>`,`<b class="${b.available?'green-text':'orange-text'}">${fmt(b.margin,2)}</b>`],['Rate at reserve (kbps)',fmt(l.maxRateKbps,2),fmt(b.maxRateKbps,2)],['Reserve criterion',l.available?'PASS':'FAIL',b.available?'PASS':'FAIL']
  ]);
  $('#pattern-source').textContent=config.patternGrid?'IMPORTED 3D GRID':config.pattern?'IMPORTED AXISYMMETRIC CUT':config.patternShape==='elliptical'?'ASSUMED TWO-PLANE MODEL':'ASSUMED COSINE MODEL';
  $('#dust-factor').textContent=`${fmt(1+8*config.dust*config.sealFactor,2)}×`;$('#shock-load').textContent=`${fmt(config.movingMass*config.shockG*9.80665,2)} N`;$('#heater-rating').textContent=`${fmt(config.heaterW)} W`;
  const s=result.summary,pass=(ok)=>`<span class="tag ${ok?'green':'orange'}">${ok?'PASS':'FAIL'}</span>`;
  $('#requirements').innerHTML=table([
    ['Final pointing error',`≤ ${fmt(config.pointingRequirement,2)}°`,`${fmt(f.error,3)}°`,pass(f.error<=config.pointingRequirement)],
    ['Final link margin',`≥ ${fmt(config.reserveDb)} dB`,`${fmt(l.margin,2)} dB`,pass(l.available)],
    ['Final 3-second RMS','Reported, no independent threshold',`${fmt(s.tailRms,3)}°`,'MEASURED IN MODEL'],
    ['Full-run peak torque',`Limited to ${fmt(config.torqueLimit,3)} N·m`,`${fmt(s.peakTorque,3)} N·m`,'ENFORCED LIMIT'],
    ['Battery budget',`< ${fmt(config.batteryWh,3)} Wh`,`${fmt(s.energyWh,4)} Wh`,pass(s.energyWh<config.batteryWh)],
    ['Command latency bound','≤ 50 ms (sampling + configured delay)',`${fmt(s.commandLatencyBoundMs,1)} ms`,pass(s.commandLatencyBoundMs<=50)],
    ['Motor settling (separate test)',stepResult?`${stepResult.stepDeg}° step`:'Run Batch analysis test',stepResult?`${fmt(stepResult.settlingMs,0)} ms`:'Not assessed','NOT COMMAND LATENCY'],
    ['2U final plate geometry','Inside envelope',f.packaging.fits?'Fits':'Outside',pass(f.packaging.fits)],
    ['2U complete assembly','CAD + cable sweep + tolerances','Not validated','NOT VERIFIED'],
    ['Entered total mass ≤ 1.5 kg','Project limit; includes adapter and cables',`${fmt(a.massKg,2)} kg`,a.projectMassPass?'WITHIN INPUT LIMIT':'OVER LIMIT'],
    ['Top surface service mass','Leaflet ≈4 kg',`${fmt(a.serviceMarginKg,2)} kg margin`,a.serviceMassPass?'WITHIN INPUT LIMIT':'OVER LIMIT'],
    ['Mass hierarchy','Antenna ≤ moving ≤ total',`${fmt(config.antennaMassG/1000,3)} / ${fmt(config.movingMass,3)} / ${fmt(a.massKg,3)} kg`,a.massConsistent?'CONSISTENT INPUTS':'INCONSISTENT INPUTS'],
    ['Top service envelope','200 × 200 × 200 mm',a.envelopeFits&&a.mountOnDeck?'2U inside; 0 mm height allowance':'Outside assumed top zone','CONCEPT GEOMETRY'],
    ['Delivered mass and host interface','Weighed BOM + provider ICD','Not verified by entered mass','NOT VERIFIED'],
    ['Shock / thermal qualification','Requires validated models and test','Sensitivity model only','NOT VERIFIED']
  ],['Assessment','Criterion','Result','Status']);
  if(tab==='radio'){rfLab?.render(config,result);patternChart($('#pattern-chart'),a=>antennaGain(a,config),antennaGain(0,config));updatePatch();}
  if(tab==='environment'){const frames=result.frames;lineChart($('#torque-chart'),[{color:green,data:frames.map(f=>({x:f.t,y:f.torque[0]}))},{color:blue,data:frames.map(f=>({x:f.t,y:f.torque[1]}))}],{xmax:config.duration,event:config.eventTime});lineChart($('#power-chart'),[{color:green,data:frames.map(f=>({x:f.t,y:f.power}))}],{xmax:config.duration,event:config.eventTime});if(thermal)drawThermal();}
  if(tab==='analysis'&&batch)scatterChart($('#batch-chart'),batch.rows);
  if(tab==='analysis'&&stepResult)drawStep();
}
function updatePatch(){try{const values=[$('#patch-f'),$('#patch-er'),$('#patch-h')];if(values.some(el=>!el.checkValidity()))throw new Error('Enter valid positive inputs within the shown ranges.');const p=patchEstimate(...values.map(el=>Number(el.value)));$('#patch-result').innerHTML=`<span><small>PATCH WIDTH</small><b>${fmt(p.widthMm,2)} <em>mm</em></b></span><span><small>PATCH LENGTH</small><b>${fmt(p.lengthMm,2)} <em>mm</em></b></span><span><small>EFFECTIVE εr</small><b>${fmt(p.effectiveEr,3)}</b></span>`;}catch(e){$('#patch-result').textContent=e.message;}}
function drawThermal(){lineChart($('#thermal-chart'),[{color:blue,data:thermal.frames.map(f=>({x:f.hours,y:f.temp}))},{color:orange,data:thermal.frames.map(f=>({x:f.hours,y:f.landerTemp}))}],{xunit:'h',threshold:config.operatingMin,xmax:Number($('#thermal-hours').value)});}
function drawStep(){lineChart($('#step-chart'),[{color:green,data:stepResult.frames.map(f=>({x:f.t,y:f.error}))}],{threshold:stepResult.bandDeg,xmax:5});}
$('#run-step').addEventListener('click',()=>{try{const input=$('#step-angle');if(!input.checkValidity())throw new Error('Step amplitude must be 0.1–30°');stepResult=runStepResponse(config,Number(input.value));$('#step-results').innerHTML=`<span>Settling time <b>${fmt(stepResult.settlingMs,0)} ms</b></span><span>10–90% rise <b>${fmt(stepResult.riseMs,0)} ms</b></span><span>Overshoot <b>${fmt(stepResult.overshootPercent,2)}%</b></span><span>50 ms slew comparison <b class="${stepResult.passes50ms?'green-text':'orange-text'}">${stepResult.passes50ms?'PASS':'FAIL'}</b></span>`;drawStep();renderStatic();}catch(e){toast(e.message,true);}});
$('#step-angle').addEventListener('change',()=>{stepResult=null;$('#step-results').textContent='Step amplitude changed. Run test again.';const canvas=$('#step-chart');canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);renderStatic();});
function reportText(){return engineeringReport(config,result,provenance)+`\n## RF extensions (v1.2)\n3D angular gain is the same function used in link calculations. Input gain convention: ${config.gainConvention}; polarization: ${config.polarizationMode}. Receiver bandwidth ${config.receiverBandwidthKHz} kHz; coding rate ${config.codingRate}; bits/symbol ${config.modulationBits}; rolloff ${config.rolloff}. Required Eb/N0 remains an independently supplied threshold at the chosen information bit rate.\n${config.patternGrid?'Imported theta/phi grid at '+config.patternGrid.frequencyGHz+' GHz; unverified source.':'Analytical or revolved 2D angular model.'} ${config.frequencyResponse?'Imported frequency response; no extrapolation; fixed angular shape.':'Scalar gain/S11/AR assumptions; not antenna bandwidth predictions.'}\nExport the RF study JSON for all cuts, sweeps and operating-point losses.\n`;}
function exportRun(kind){if(pendingTimer){recalculate(false);pendingTimer=null;}const stamp=new Date().toISOString().slice(0,19).replace(/[:T]/g,'-'),base=`lunar-link-${config.scenario}-${stamp}`;
  if(kind==='csv')download(base+'.csv',csvExport(result),'text/csv');
  if(kind==='json')download(base+'.json',JSON.stringify({schemaVersion:1,createdAt:new Date().toISOString(),modelVersion:MODEL_VERSION,config,provenance,summary:result.summary,frames:result.frames,batch,thermal,stepResponse:stepResult,rfStudy:rfLab?.result===result?rfLab.study:null,referenceBasis:'src/research.js; see exported engineering report'},null,2),'application/json');
  if(kind==='report'){let report=reportText();if(stepResult)report+=`\n## Separate motor step test\n${stepResult.stepDeg} deg step; +/-${stepResult.bandDeg} deg band; settling ${fmt(stepResult.settlingMs,0)} ms; rise ${fmt(stepResult.riseMs,0)} ms. Simulated, not bench validated.\n`;download(base+'.md',report,'text/markdown');}
  if(kind==='png'){if(!scene){toast('3D rendering unavailable',true);return;}const a=document.createElement('a');a.href=scene.capture();a.download=base+'.png';a.click();}
  $('.export-menu').open=false;
}

$('#antenna-profile').addEventListener('change',e=>{if(e.target.value==='custom'){config.antennaProfile='custom';}else config=applyAntennaProfile(config,e.target.value);invalidateAnalysis();populate();recalculate(false);});
for(const el of $$('[data-param]'))el.addEventListener('change',()=>editParam(el.dataset.param,el.value===''?NaN:Number(el.value)));
for(const el of $$('[data-range]'))el.addEventListener('input',()=>editParam(el.dataset.range,Number(el.value)));
$('#jam-axis').addEventListener('change',e=>{config.jamAxis=e.target.value;invalidateAnalysis();recalculate(false);});
for(const el of $$('[data-preset]'))el.addEventListener('click',()=>{activePreset=el.dataset.preset;config=presetConfig(activePreset);provenance={};invalidateAnalysis();populate();recalculate(true);});
$('#reset-config').addEventListener('click',()=>{config=presetConfig(activePreset);provenance={};invalidateAnalysis();populate();recalculate(false);toast('Preset defaults restored');});
$('#run').addEventListener('click',()=>recalculate(true));
$('#play').addEventListener('click',()=>{if(time>=config.duration)time=0;setPlaying(!playing);renderFrame();});
$('#rewind').addEventListener('click',()=>{time=0;setPlaying(false);renderFrame();});
$('#timeline').addEventListener('input',e=>{time=Number(e.target.value);setPlaying(false);renderFrame();});
$('#speed').addEventListener('change',e=>{speed=Number(e.target.value);});
for(const el of $$('[data-tab]'))el.addEventListener('click',()=>{tab=el.dataset.tab;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b===el);b.setAttribute('aria-selected',b===el?'true':'false');});$$('.tab-panel').forEach(p=>p.hidden=p.id!==`panel-${tab}`);if(tab!=='mission')setPlaying(false);requestAnimationFrame(()=>{scene?.resize();renderStatic();renderFrame();});});
for(const el of $$('[data-view]'))el.addEventListener('click',()=>{scene?.setView(el.dataset.view);$$('[data-view]').forEach(b=>b.classList.toggle('active',b===el));});
$('#show-beam').addEventListener('change',e=>{if(scene)scene.beamVisible=e.target.checked;renderFrame();});$('#explode').addEventListener('change',e=>{if(scene){scene.exploded=e.target.checked;if(scene.detail)scene.setView('detail');}renderFrame();});
$('#show-zones').addEventListener('change',e=>{scene?.setBrochureVisible(e.target.checked);});
$('#payload-cover').addEventListener('change',e=>{if(scene)scene.payloadCover.visible=e.target.checked;});
$('#studio-view').addEventListener('change',e=>{scene?.setStudio(e.target.checked);$('#scene').classList.toggle('white-studio',e.target.checked);});
$('#export-design').addEventListener('click',()=>{if(pendingTimer)recalculate(false);download('payload-assembly-and-host-bus.json',JSON.stringify(exportDesign(config,result),null,2),'application/json');});
$('#export-model').addEventListener('click',async()=>{if(!scene)return;const button=$('#export-model');button.disabled=true;try{if(pendingTimer)recalculate(false);const data=await scene.exportModel();download('ispace-photo-concept-with-our-2u.glb',data,'model/gltf-binary');toast('3D model exported in metres; photo reconstruction, not provider CAD');}catch(e){toast(e.message,true);}finally{button.disabled=false;}});
$('#surface-mount').addEventListener('click',()=>{[config.mountX,config.mountY,config.mountZ]=SURFACE.mount;for(const k of ['mountX','mountY','mountZ'])provenance[k]='Top green zone concept coordinate; not provider CAD';invalidateAnalysis();populate();recalculate(false);scene?.setView('mount');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='mount'));toast('Top green-zone concept mount restored');});
for(const el of $$('[data-export]'))el.addEventListener('click',()=>exportRun(el.dataset.export));$('#export-report').addEventListener('click',()=>exportRun('report'));
$('#import-config').addEventListener('click',()=>$('#file-config').click());
$('#file-config').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>30e6)throw new Error('Scenario file is too large (30 MB maximum)');const input=JSON.parse(await file.text());if(!input.config && !('frequencyGHz' in input))throw new Error('Expected an exported scenario or configuration object');config=validateConfig(input.config||input);activePreset=config.scenario;provenance=Object.fromEntries(Object.keys(config).map(k=>[k,'Imported user input; unverified']));invalidateAnalysis();populate();recalculate(false);toast('Scenario imported and recalculated');}catch(err){toast(err.message,true);}e.target.value='';});
$('#import-pattern').addEventListener('click',()=>$('#file-pattern').click());$('#file-pattern').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw new Error('Pattern file too large (2 MB maximum)');config.pattern=parsePatternCSV(await file.text());config.patternGrid=null;provenance.pattern=`Imported file: ${file.name}; source unverified`;invalidateAnalysis();recalculate(false);toast(`Imported ${config.pattern.length} pattern samples`);}catch(err){toast(err.message,true);}e.target.value='';});
$('#clear-pattern').addEventListener('click',()=>{config.pattern=null;config.patternGrid=null;invalidateAnalysis();recalculate(false);toast('Analytical cosine pattern restored');});
for(const id of ['#patch-f','#patch-er','#patch-h'])$(id).addEventListener('input',updatePatch);
$('#run-thermal').addEventListener('click',()=>{thermal=runThermal(config,Number($('#thermal-hours').value));const lost=thermal.frames.find(f=>!f.powered);$('#thermal-results').innerHTML=`<span>Minimum <b>${fmt(thermal.minTemp,1)} °C</b></span><span>Maximum <b>${fmt(thermal.maxTemp,1)} °C</b></span><span>Heater energy <b>${fmt(thermal.heaterWh,2)} Wh</b></span><span>Battery <b>${lost?`depleted by ${fmt(lost.hours,1)} h`:'not depleted'}</b></span>`;drawThermal();});
$('#thermal-hours').addEventListener('change',()=>{thermal=null;$('#thermal-results').textContent='Duration changed. Run thermal study again.';const canvas=$('#thermal-chart');canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);});
function wilson(success,n){const z=1.96,p=success/n,d=1+z*z/n,mid=(p+z*z/(2*n))/d,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return `${fmt((mid-half)*100,1)}–${fmt((mid+half)*100,1)}%`;}
$('#run-batch').addEventListener('click',()=>{if(worker)worker.terminate();batch=null;$('#export-batch').disabled=true;$('#batch-results').textContent='Analysis running…';worker=new Worker(new URL('./analysis.worker.js',import.meta.url),{type:'module'});$('#run-batch').disabled=true;$('#cancel-batch').hidden=false;$('#batch-progress').hidden=false;$('#batch-progress i').style.width='0%';$('#batch-status').textContent='Sampling landing conditions…';const count=Number($('#batch-count').value);
  worker.onmessage=({data})=>{if(data.type==='progress'){$('#batch-progress i').style.width=`${data.done/data.count*100}%`;$('#batch-status').textContent=`Simulating ${data.done} / ${data.count} paired scenarios…`;}
    if(data.type==='done'){batch=data;const n=data.rows.length,g=data.rows.filter(r=>r.pass).length,f=data.rows.filter(r=>r.fixedPass).length;$('#batch-results').innerHTML=table([['Passed trials',`${g} / ${n}`,`${f} / ${n}`],['Scenario pass rate',`${fmt(g/n*100,1)}%`,`${fmt(f/n*100,1)}%`],['95% Wilson interval',wilson(g,n),wilson(f,n)]],['Metric','Gimbal','Fixed'])+`<p class="small-note">Seed ${data.seed} · success means ≥95% post-acquisition-window link availability. Intervals apply only to the declared sampling distribution. Uniform Euler angles are not uniform orientations on a sphere.</p>`;$('#batch-status').textContent=`Completed ${n} paired scenarios · seed ${data.seed}`;$('#export-batch').disabled=false;scatterChart($('#batch-chart'),data.rows);finishBatch();}
    if(data.type==='error'){toast(data.message,true);finishBatch();}};
  worker.onerror=e=>{toast(e.message||'Analysis worker failed',true);finishBatch();};worker.postMessage({config,count,seed:config.seed});
});
function finishBatch(){worker?.terminate();worker=null;$('#run-batch').disabled=false;$('#cancel-batch').hidden=true;$('#batch-progress').hidden=true;}
$('#cancel-batch').addEventListener('click',()=>{finishBatch();$('#batch-status').textContent='Analysis cancelled. No partial result is presented.';$('#batch-results').textContent='Run again to produce a complete batch.';});
$('#export-batch').addEventListener('click',()=>{if(!batch)return;const keys=Object.keys(batch.rows[0]);download('lunar-link-monte-carlo.csv',keys.join(',')+'\n'+batch.rows.map(r=>keys.map(k=>r[k]).join(',')).join('\n'),'text/csv');});
$('.brand').addEventListener('click',e=>{e.preventDefault();$('[data-tab="mission"]').click();});
window.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();$('#play').click();}});
window.addEventListener('resize',()=>{renderStatic();renderFrame();});

try{scene=new MissionScene($('#scene'));}catch(e){$('#scene').innerHTML='<div class="webgl-fallback"><b>3D rendering could not start</b><p>Enable hardware acceleration or open this page in a WebGL-capable browser. Numerical simulation and exports still work.</p></div>';toast('WebGL unavailable. Numerical model remains usable.',true);}
rfLab=new RFLab((patch,source='User RF input; unverified')=>{try{config=validateConfig({...config,...patch});for(const key of Object.keys(patch))provenance[key]=source;invalidateAnalysis();populate();recalculate(false);}catch(e){toast(e.message,true);}},toast,()=>({...provenance}),()=>{if(pendingTimer)recalculate(false);});
populate();recalculate(false);
let previous=performance.now(),lastUI=0;
function animate(now){const dt=Math.min((now-previous)/1000,0.1);previous=now;if(playing){time=Math.min(config.duration,time+dt*speed);if(time>=config.duration)setPlaying(false);}if(now-lastUI>80){if(tab==='mission')renderFrame();lastUI=now;}if(tab==='mission')scene?.render();if(tab==='radio')rfLab?.tick();requestAnimationFrame(animate);}
requestAnimationFrame(animate);
// Read-only diagnostics are useful for automated browser checks and independent review.
window.lunarLink={get result(){return result;},get config(){return {...config};},get batch(){return batch;},get thermal(){return thermal;},get stepResponse(){return stepResult;},get rfStudy(){return rfLab?.study;},get rfWebgl(){return Boolean(rfLab?.scene);},get webgl(){return Boolean(scene);}};
