import {linkBudget} from './engine.js';
import {directionalGain,rfState,patternMetrics,parseGridCSV,parseResponseCSV,gridImportPatch,exportPatternCSV} from './antenna-rf.js';
import {RadiationScene} from './radiation-scene.js';
import {lineChart} from './charts.js';
import {REFERENCES} from './research.js';
const $=s=>document.querySelector(s),fmt=(v,n=2)=>v===null||!Number.isFinite(v)?'—':v.toFixed(n);
const green='#cced9c',blue='#8ab9e6',orange='#e9a278';
const chart=(id,title,note)=>`<article class="card"><div class="card-heading"><h2>${title}</h2></div><canvas id="${id}" class="chart tall" role="img" aria-label="${title}"></canvas><p class="card-padding small-note">${note}</p></article>`;
export const RF_LAB_HTML=`<div class="section-intro"><div><h2>Antenna & link laboratory</h2><p>รูปแบบรังสี → gain ไปยังโลก → received power → C/N₀ → Eb/N₀ → link margin</p></div><span class="tag">REFERENCE + ASSUMPTION + IMPORT</span></div>
<article class="card rf-controls"><div class="card-padding"><div class="rf-inputs"><label>Pattern model<select id="rf-shape"><option value="symmetric">Symmetric cosine (assumed)</option><option value="elliptical">Two-plane cosine (assumed)</option></select></label><label>Gain input convention<select id="rf-convention"><option value="realized">Realized gain: mismatch already included</option><option value="accepted">Accepted-power gain: subtract S11 mismatch</option></select></label><label>Polarization model<select id="rf-polarization"><option value="fixed">User fixed loss</option><option value="same">Total gain → ideal matched-sense CP receiver</option><option value="opposite">Total gain → ideal opposite-sense CP receiver</option></select></label><label>3D radius<select id="rf-radius"><option value="db">Relative dB: −30 to 0 dB</option><option value="linear">Normalized linear power</option></select></label></div><p class="small-note">Computed CP loss assumes input total gain and an ideal circular receive polarization. If imported gain is already the matching CP component (dBic), use fixed loss for additional receiver mismatch only. ไม่หัก polarization หรือ S11 ซ้ำกับ gain ที่รวมผลนั้นแล้ว</p><div class="button-row"><button id="rf-import-grid" class="button">Import 3D pattern CSV</button><button id="rf-import-response" class="button">Import frequency response CSV</button><button id="rf-clear-data" class="button ghost">Clear RF imports</button><button id="rf-export-data" class="button">Export RF study JSON</button><button id="rf-export-grid" class="button">Export current 3D grid</button><button id="rf-export-png" class="button">3D PNG</button></div><p id="rf-data-status" class="small-note"></p><details class="rf-schema"><summary>CSV formats and synthetic examples</summary><p>3D: <code>frequency_ghz,theta_deg,phi_deg,gain_dbi</code> · Complete θ×φ grid, θ includes 0/180°, φ includes 0° and excludes 360°; one frequency per file.</p><p>Response: <code>frequency_ghz,s11_db,gain_dbi,axial_ratio_db</code> · At least two unique frequencies; no extrapolation.</p><p><a href="/example-3d-pattern.csv" download>Synthetic 3D example</a> · <a href="/example-frequency-response.csv" download>Synthetic frequency example</a> — demonstration only, not measurements.</p></details><label class="rf-timeline">Inspect mission time <input id="rf-time" type="range" min="0" max="18" step="0.04" value="18"><b id="rf-time-label">T+18 s</b></label></div></article>
<div class="two-column"><article class="card"><div class="card-heading"><h2>3D radiation pattern · antenna frame</h2><span class="tag" id="rf-source">ANALYTICAL</span></div><div id="rf-scene" class="rf-scene"></div><div class="card-padding"><div class="rf-colorbar"></div><p id="rf-scale" class="small-note"></p><p class="small-note">+Z boresight (blue axis); φ=0 along +X (red), φ=90° along +Y (green). White arrow = Earth LOS at selected time in antenna coordinates. Radius is a plotting scale, not distance or a hard coverage boundary. Drag to orbit.</p></div></article><article class="card"><div class="card-heading"><h2>θ–φ gain map</h2></div><canvas id="rf-map" class="rf-map" role="img" aria-label="Theta phi gain heatmap"></canvas><p class="card-padding small-note">X: φ 0–360° · Y: θ 0–180° from boresight. Same angular function as the 3D surface and live link budget. The map is intrinsic antenna response; lander blockage remains a separate LOS gate.</p></article></div>
<article class="card"><div class="card-heading"><h2>RF operating point & evidence</h2></div><div id="rf-metrics" class="card-padding"></div></article>
<div class="two-column">${chart('rf-cuts','Principal-plane gain cuts · dBi','Green φ=0°, blue φ=90°. These are principal cuts; CP antennas do not have one unique linear E/H plane. Negative θ uses the opposite azimuth.')}${chart('rf-angle','Link margin vs mispointing · dB','Two principal cuts in a clear, powered path; dashed line is required reserve. This sweep does not grant mechanical reach or remove lander obstruction.')}</div>
<div class="two-column">${chart('rf-frequency','Gain vs frequency · dBi','Green boresight, orange selected gimbal direction. Without imported response: held-gain sensitivity only, not an antenna bandwidth prediction.')}${chart('rf-s11','S11 vs frequency · dB','Reflection coefficient magnitude in dB (negative); dashed −10 dB screening line. Flat scalar assumption until a response CSV is imported.')}</div>
<div class="two-column">${chart('rf-ar','Axial ratio vs frequency · dB','Dashed 3 dB is a common CP screening criterion, not this mission’s verified requirement. No angle-dependent AR data are inferred.')}${chart('rf-fmargin','Link margin vs frequency · dB','Green on-axis clear-path reference; orange actual selected geometry/power. Gaps mean unsupported frequency, blocked LOS or lost RF power.')}</div>
<div class="two-column">${chart('rf-rate','Margin vs information bit rate · dB','X is log10(kbps). Green on-axis; orange selected geometry. Receiver bandwidth constraint is applied independently of Eb/N0 margin.')}${chart('rf-range','Margin vs range · dB','Same frequency, gain and ground-station G/T. A range sweep is not an orbital ephemeris or a lunar relay service model.')}</div>
<article class="card"><div class="card-heading"><h2>One-variable sensitivity · selected RF direction</h2></div><div id="rf-sensitivity" class="card-padding"></div></article>
<article class="card"><div class="card-heading"><h2>Parameters that need evidence before the final review</h2></div><div class="card-padding"><p><b>Antenna:</b> realized/co-polar gain, θ–φ pattern at each frequency, HPBW both cuts, sidelobes/backlobes, S11/VSWR, axial ratio and efficiency; test installed on a representative lander.</p><p><b>Link:</b> RF power at a defined port, feed loss, receiver G/T, bandwidth, information bit rate, coding rate/modulation, required Eb/N0 at stated BER/FER, polarization and implementation losses, range, elevation and blockage.</p><p><b>Environment/control:</b> antenna temperature, measured resonance shift, installation changes, mounting position, gimbal travel/2U collision, lock/release, steady error, acquisition time and bus availability. Dust-induced RF loss must come from measurement, not an invented multiplier.</p><p>Suggested evidence mapping for Proposal (2): PDF p.9 open technical slot; p.14 control evidence; p.15 shock and p.16 thermal coupling; p.17 verification plan. A peak-gain paper value alone cannot populate measured S11/AR/3D tables. No full-wave EM or shock/thermal qualification is generated.</p></div></article>
<input id="rf-grid-file" type="file" accept=".csv" hidden><input id="rf-response-file" type="file" accept=".csv" hidden>`;
function table(rows){return `<table><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<${i?'td':'th'}>${x}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table>`;}
function save(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export class RFLab{
 constructor(change,toast,getProvenance=()=>({}),beforeExport=()=>{}){this.beforeExport=beforeExport;this.getProvenance=getProvenance;this.change=change;this.toast=toast;this.rows=null;try{this.scene=new RadiationScene($('#rf-scene'));}catch{$('#rf-scene').textContent='WebGL unavailable; RF calculations and charts remain available.';}
  for(const [id,key] of [['rf-shape','patternShape'],['rf-convention','gainConvention'],['rf-polarization','polarizationMode']])$('#'+id).addEventListener('change',e=>change(key==='patternShape'?{[key]:e.target.value,antennaProfile:'custom',pattern:null,patternGrid:null}:{[key]:e.target.value},key==='patternShape'?'User selected an analytical pattern model':'User RF input; unverified'));
  $('#rf-radius').addEventListener('change',()=>this.render(this.c,this.result));$('#rf-time').addEventListener('input',()=>{clearTimeout(this.timer);this.timer=setTimeout(()=>this.render(this.c,this.result),50);});
  for(const [button,input,key,parser] of [['rf-import-grid','rf-grid-file','patternGrid',parseGridCSV],['rf-import-response','rf-response-file','frequencyResponse',parseResponseCSV]]){
   $('#'+button).addEventListener('click',()=>$('#'+input).click());$('#'+input).addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8e6)throw new Error('RF import maximum 8 MB');const value=parser(await file.text());change(key==='patternGrid'?gridImportPatch(value):{[key]:value},`Imported ${file.name}; unverified source`);toast('RF data imported and link recalculated');}catch(err){toast(err.message,true);}e.target.value='';});
  }
  $('#rf-clear-data').addEventListener('click',()=>change({patternGrid:null,frequencyResponse:null}));
  $('#rf-export-data').addEventListener('click',()=>{this.refreshForExport();save('antenna-rf-study.json',JSON.stringify(this.study,null,2));});
  $('#rf-export-png').addEventListener('click',()=>{this.refreshForExport();if(!this.scene)return;const a=document.createElement('a');a.href=this.scene.capture();a.download='radiation-pattern.png';a.click();});
  $('#rf-export-grid').addEventListener('click',()=>{try{this.refreshForExport();save('radiation-pattern-generated.csv',exportPatternCSV(this.c,this.frame.temp),'text/csv');}catch(e){this.toast(e.message,true);}});
 }
 refreshForExport(){this.beforeExport();clearTimeout(this.timer);this.render(this.c,this.result);}
 render(c,result){if(!c||!result)return;const changed=this.result!==result;this.c=c;this.result=result;if(changed){$('#rf-time').max=c.duration;$('#rf-time').value=c.duration;}
  const time=Number($('#rf-time').value),f=result.frames.reduce((best,x)=>Math.abs(x.t-time)<Math.abs(best.t-time)?x:best,result.frames[0]);this.frame=f;
  $('#rf-shape').value=c.patternShape;$('#rf-convention').value=c.gainConvention;$('#rf-polarization').value=c.polarizationMode;$('#rf-time-label').textContent=`T+${fmt(f.t)} s`;
  const source=c.patternGrid?'IMPORTED θ–φ GRID':c.pattern?'REVOLVED 2D CUT':c.patternShape==='elliptical'?'ASSUMED TWO-PLANE MODEL':'ASSUMED COSINE MODEL';$('#rf-source').textContent=source;
  const rf=rfState(c,f.temp),metrics=patternMetrics(c,f.temp),l=f.link,shown=(v,n=2)=>fmt(rf.supported?v:null,n);
  $('#rf-data-status').textContent=`${source}. ${c.frequencyResponse?'Frequency CSV interpolation, no extrapolation; angular shape held constant across frequency.':'No frequency response imported: scalar gain/S11/AR assumptions and fixed angular shape; frequency changes FSPL, not a predicted resonance.'} ${c.patternGrid?`Grid reference frequency ${c.patternGrid.frequencyGHz} GHz (source not verified).`:''} ${c.patternGrid?.snapshot?`Evaluated snapshot at ${c.patternGrid.snapshot.temperatureC.toFixed(2)}°C: matching/AR frozen; included gain losses will not be subtracted again.`:''} Thermal coefficient ${c.rfTempCoeffPpm} ppm/°C is a user sensitivity assumption. 2D CSV is overridden while a 3D grid is loaded.`;
  this.scene?.update(c,f,$('#rf-radius').value==='linear');$('#rf-scale').textContent=!rf.supported?'No supported pattern at the selected frequency/temperature. Import data that cover this operating point.':`Blue ≤ ${fmt((this.scene?.peak??metrics.peakGain)-30)} dBi → red ${fmt(this.scene?.peak??metrics.peakGain)} dBi. θ=${fmt(f.rfAngles.theta)}°, φ=${fmt(f.rfAngles.phi)}° to Earth.`;
  this.drawMap(c,f,this.scene?.peak??metrics.peakGain);
  $('#rf-metrics').innerHTML=table([
   ['Selected actual link',l.available?'PASS':'FAIL',f.blockedReason||(!f.rfPowered?'RF POWER LOST':!rf.supported?'FREQUENCY DATA UNSUPPORTED':!l.bandwidthPass?'RECEIVER BANDWIDTH EXCEEDED':'LOS clear; assess margin')],
   ['Antenna input',`${c.frequencyGHz} GHz; ${fmt(f.temp,1)} °C`,`lookup ${fmt(rf.queryFrequencyGHz,6)} GHz`],
   ['Directional gain / pointing loss',`${shown(l.gain)} dBi / ${shown(l.pointingLoss)} dB`,source],
   ['S11 / VSWR',`${shown(rf.s11Db)} dB / ${shown(rf.vswr)}`,c.patternGrid?.snapshot?'Frozen evaluated snapshot':c.frequencyResponse?'Imported interpolation':'Scalar assumption'],
   ['Mismatch loss / applied',`${shown(rf.mismatchLoss,3)} / ${shown(rf.appliedMismatchLoss,3)} dB`,c.gainConvention==='realized'?'Already included in realized gain':'Applied once'],
   ['Axial ratio / polarization loss',`${shown(rf.axialRatioDb)} / ${shown(rf.polarizationLoss,3)} dB`,c.polarizationMode==='fixed'?'Fixed loss assumption':'Ideal CP receiver; input total gain required'],
   ['Evaluated pattern integral / directivity',`${shown(metrics.integratedEfficiency*100,1)}% / ${shown(metrics.directivityDbi)} dBi`,!rf.supported?'UNSUPPORTED':metrics.integratedEfficiency>1.02?'INCONSISTENT >100%; gain normalization requires review':'Includes applied gain losses and frequency/temperature lookup; not measured radiation efficiency'],
   ['EIRP / FSPL',`${shown(l.eirp)} dBW / ${fmt(l.pathLoss)} dB`,'Same gain as 3D pattern'],
   ['Received / noise power',`${fmt(l.receivedDbm)} / ${fmt(l.noiseDbm)} dBm`,`Rx gain ${fmt(l.receiverGain)} dBi implied by G/T and Tsys`],
   ['C/N / C/N₀ / Eb/N₀',`${fmt(l.cnDb)} dB / ${l.margin===null?'—':fmt(l.cn0)} dB-Hz / ${l.margin===null?'—':fmt(l.ebno)} dB`,'No extra coding gain added'],
   ['Info / coded / symbol rate',`${fmt(c.bitrateKbps)} kbps / ${fmt(c.bitrateKbps/c.codingRate)} kbps / ${fmt(l.symbolRate/1000)} ksym/s`,'Coding rate and bits/symbol affect bandwidth, not threshold automatically'],
   ['Occupied / receiver bandwidth',`${fmt(l.occupiedBandwidthKHz)} / ${fmt(c.receiverBandwidthKHz)} kHz`,l.bandwidthPass?'PASS':'FAIL'],
   ['Margin / reserve / supported max rate',`${fmt(l.margin)} / ${fmt(c.reserveDb)} dB / ${fmt(l.maxRateKbps)} kbps`,'Max rate limited by both RF energy and bandwidth']]);
  const cuts=[],angles=[],freq=[],rates=[],ranges=[];
  for(let a=-180;a<=180;a+=2)cuts.push({x:a,h:directionalGain(Math.abs(a),a<0?180:0,c,f.temp),v:directionalGain(Math.abs(a),a<0?270:90,c,f.temp)});
  for(let a=0;a<=90;a++)angles.push({x:a,h:linkBudget(a,c,false,true,0,f.temp).margin,v:linkBudget(a,c,false,true,90,f.temp).margin});
  const lo=c.frequencyResponse?.[0].frequencyGHz??c.frequencyGHz*0.9,hi=c.frequencyResponse?.at(-1).frequencyGHz??c.frequencyGHz*1.1;
  for(let i=0;i<=100;i++){const x=lo+(hi-lo)*i/100,cc={...c,frequencyGHz:x},state=rfState(cc,f.temp),on=linkBudget(0,cc,false,true,0,f.temp),actual=linkBudget(f.error,cc,f.blocked,f.rfPowered,f.rfAngles.phi,f.temp);freq.push({x,gain:state.supported?directionalGain(0,0,cc,f.temp):null,actualGain:state.supported?actual.gain:null,s11:state.supported?state.s11Db:null,ar:state.supported?state.axialRatioDb:null,margin:on.margin,actualMargin:actual.margin});}
  for(let i=0;i<=100;i++){const x=-2+i*0.06,cc={...c,bitrateKbps:10**x},on=linkBudget(0,cc,false,true,0,f.temp),actual=linkBudget(f.error,cc,f.blocked,f.rfPowered,f.rfAngles.phi,f.temp);rates.push({x,kbps:10**x,on:on.bandwidthPass?on.margin:null,actual:actual.bandwidthPass?actual.margin:null});const range=c.distanceKm*(0.5+i/100),rc={...c,distanceKm:range};ranges.push({x:range,on:linkBudget(0,rc,false,true,0,f.temp).margin,actual:linkBudget(f.error,rc,f.blocked,f.rfPowered,f.rfAngles.phi,f.temp).margin});}
  const plot=(id,data,keys,options={})=>lineChart($('#'+id),keys.map((key,i)=>({color:i===0?green:['rf-cuts','rf-angle'].includes(id)?blue:orange,data:data.map(r=>({x:r.x,y:r[key]}))})),{xmin:data[0].x,xmax:data.at(-1).x,...options});
  plot('rf-cuts',cuts,['h','v'],{xunit:'°'});plot('rf-angle',angles,['h','v'],{xunit:'°',threshold:c.reserveDb});plot('rf-frequency',freq,['gain','actualGain'],{xunit:'GHz'});plot('rf-s11',freq,['s11'],{xunit:'GHz',threshold:-10});plot('rf-ar',freq,['ar'],{xunit:'GHz',threshold:3});plot('rf-fmargin',freq,['margin','actualMargin'],{xunit:'GHz',threshold:c.reserveDb});plot('rf-rate',rates,['on','actual'],{xunit:'',threshold:c.reserveDb});plot('rf-range',ranges,['on','actual'],{xunit:'km',threshold:c.reserveDb});
  const sensitivity=[['TX power ×2',{txPowerW:c.txPowerW*2}],['Range ×2',{distanceKm:c.distanceKm*2}],['Information rate ×2',{bitrateKbps:c.bitrateKbps*2}],['Receiver G/T +1 dB',{receiverGT:c.receiverGT+1}],['Cable loss +1 dB',{cableLoss:c.cableLoss+1}],['Installation loss +1 dB',{installationLossDb:c.installationLossDb+1}]].map(([label,patch])=>{const s=linkBudget(f.error,{...c,...patch},false,true,f.rfAngles.phi,f.temp);return {parameter:label,deltaDb:s.rawMargin-l.rawMargin,bandwidthPass:s.bandwidthPass};});
  $('#rf-sensitivity').innerHTML=table(sensitivity.map(s=>[s.parameter,`${s.deltaDb>=0?'+':''}${fmt(s.deltaDb,3)} dB`,s.bandwidthPass?'Bandwidth OK':'Bandwidth exceeded']))+'<p class="small-note">RF deltas at the same pointing direction; blockage and power loss still prevent communication. These are deterministic what-if changes, not independent random error terms.</p>';
  this.study={modelVersion:result.modelVersion,createdAt:new Date().toISOString(),source,provenance:this.getProvenance(),config:c,selectedTime:f.t,operatingPoint:l,patternMetrics:metrics,cuts,angleSweep:angles,frequencySweep:freq,rateSweep:rates,rangeSweep:ranges,sensitivity,references:REFERENCES,limitations:['Analytical or user-imported data, not EM solved here','Frequency response interpolation with fixed angular shape','No angle-dependent axial ratio model','No terrain diffraction, multipath, surface-wave or dust dielectric model']};
 }
 drawMap(c,f,peak){const canvas=$('#rf-map'),rect=canvas.getBoundingClientRect();if(!rect.width)return;canvas.width=Math.round(rect.width);canvas.height=320;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=35,nx=72,ny=36;if(peak===null){ctx.fillStyle='#b7c5d0';ctx.font='13px system-ui';ctx.fillText('No supported angular gain data',p,h/2);return;}const values=[];for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const g=directionalGain((y+0.5)*180/ny,(x+0.5)*360/nx,c,f.temp);values.push(g);}let i=0;for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const u=Math.max(0,Math.min(1,(values[i++]-peak+30)/30));ctx.fillStyle=`hsl(${234*(1-u)} 85% 52%)`;ctx.fillRect(p+x*(w-2*p)/nx,p+y*(h-2*p)/ny,Math.ceil((w-2*p)/nx),Math.ceil((h-2*p)/ny));}ctx.fillStyle='#b7c5d0';ctx.font='10px system-ui';ctx.textAlign='center';for(let j=0;j<=4;j++){ctx.fillText(`${j*90}°`,p+j*(w-2*p)/4,h-12);ctx.fillText(`${j*45}°`,16,p+j*(h-2*p)/4+3);}ctx.strokeStyle='white';const x=p+f.rfAngles.phi/360*(w-2*p),y=p+f.rfAngles.theta/180*(h-2*p);ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.stroke();}
 tick(){this.scene?.render();}
}
